/* Generated By:JavaCC: Do not edit this line. AnalizadorLexicoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorLexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Letra = 1;
  /** RegularExpression Id. */
  int Numero = 2;
  /** RegularExpression Id. */
  int Pregunta = 3;
  /** RegularExpression Id. */
  int Entonces = 4;
  /** RegularExpression Id. */
  int ParenIzq = 5;
  /** RegularExpression Id. */
  int ParenDer = 6;
  /** RegularExpression Id. */
  int Comilla = 7;
  /** RegularExpression Id. */
  int Apost = 8;
  /** RegularExpression Id. */
  int Comillas = 9;
  /** RegularExpression Id. */
  int Char = 10;
  /** RegularExpression Id. */
  int Int = 11;
  /** RegularExpression Id. */
  int Float = 12;
  /** RegularExpression Id. */
  int Double = 13;
  /** RegularExpression Id. */
  int String = 14;
  /** RegularExpression Id. */
  int Bool = 15;
  /** RegularExpression Id. */
  int Var = 16;
  /** RegularExpression Id. */
  int Byte = 17;
  /** RegularExpression Id. */
  int Long = 18;
  /** RegularExpression Id. */
  int Short = 19;
  /** RegularExpression Id. */
  int Ulong = 20;
  /** RegularExpression Id. */
  int Uint = 21;
  /** RegularExpression Id. */
  int Sbyte = 22;
  /** RegularExpression Id. */
  int Ushort = 23;
  /** RegularExpression Id. */
  int Nchar = 24;
  /** RegularExpression Id. */
  int Varchar = 25;
  /** RegularExpression Id. */
  int DATE = 26;
  /** RegularExpression Id. */
  int DATETIME = 27;
  /** RegularExpression Id. */
  int Numeric = 28;
  /** RegularExpression Id. */
  int NVARCHAR = 29;
  /** RegularExpression Id. */
  int Bit = 30;
  /** RegularExpression Id. */
  int TipoDato = 31;
  /** RegularExpression Id. */
  int LlaveIzq = 32;
  /** RegularExpression Id. */
  int LlaveDer = 33;
  /** RegularExpression Id. */
  int PuntoYComa = 34;
  /** RegularExpression Id. */
  int IgualIgual = 35;
  /** RegularExpression Id. */
  int MenorQue = 36;
  /** RegularExpression Id. */
  int MayorQue = 37;
  /** RegularExpression Id. */
  int DiferenteDe = 38;
  /** RegularExpression Id. */
  int MenorIgual = 39;
  /** RegularExpression Id. */
  int MayorIgual = 40;
  /** RegularExpression Id. */
  int AccesoMiembro = 41;
  /** RegularExpression Id. */
  int Sustitucion = 42;
  /** RegularExpression Id. */
  int Public = 43;
  /** RegularExpression Id. */
  int Static = 44;
  /** RegularExpression Id. */
  int Private = 45;
  /** RegularExpression Id. */
  int TipoAcceso = 46;
  /** RegularExpression Id. */
  int Do = 47;
  /** RegularExpression Id. */
  int For = 48;
  /** RegularExpression Id. */
  int Foreach = 49;
  /** RegularExpression Id. */
  int While = 50;
  /** RegularExpression Id. */
  int SelectivaMultiple = 51;
  /** RegularExpression Id. */
  int Else = 52;
  /** RegularExpression Id. */
  int Finally = 53;
  /** RegularExpression Id. */
  int Default = 54;
  /** RegularExpression Id. */
  int Asignar = 55;
  /** RegularExpression Id. */
  int Case = 56;
  /** RegularExpression Id. */
  int Metodo = 57;
  /** RegularExpression Id. */
  int ClaseConsole = 58;
  /** RegularExpression Id. */
  int Sobrecargar = 59;
  /** RegularExpression Id. */
  int Concat = 60;
  /** RegularExpression Id. */
  int Length = 61;
  /** RegularExpression Id. */
  int Write = 62;
  /** RegularExpression Id. */
  int WriteLine = 63;
  /** RegularExpression Id. */
  int Delete = 64;
  /** RegularExpression Id. */
  int Include = 65;
  /** RegularExpression Id. */
  int Substring = 66;
  /** RegularExpression Id. */
  int ToChar = 67;
  /** RegularExpression Id. */
  int ToUpper = 68;
  /** RegularExpression Id. */
  int ToLower = 69;
  /** RegularExpression Id. */
  int ToString = 70;
  /** RegularExpression Id. */
  int Next = 71;
  /** RegularExpression Id. */
  int AVG = 72;
  /** RegularExpression Id. */
  int Count = 73;
  /** RegularExpression Id. */
  int Max = 74;
  /** RegularExpression Id. */
  int Min = 75;
  /** RegularExpression Id. */
  int Sum = 76;
  /** RegularExpression Id. */
  int Estructura = 77;
  /** RegularExpression Id. */
  int CapExcepcion = 78;
  /** RegularExpression Id. */
  int Namespace = 79;
  /** RegularExpression Id. */
  int Intenta = 80;
  /** RegularExpression Id. */
  int Romper = 81;
  /** RegularExpression Id. */
  int Base = 82;
  /** RegularExpression Id. */
  int Checked = 83;
  /** RegularExpression Id. */
  int BackColor = 84;
  /** RegularExpression Id. */
  int Font = 85;
  /** RegularExpression Id. */
  int Text = 86;
  /** RegularExpression Id. */
  int Enabled = 87;
  /** RegularExpression Id. */
  int TextAling = 88;
  /** RegularExpression Id. */
  int True = 89;
  /** RegularExpression Id. */
  int False = 90;
  /** RegularExpression Id. */
  int List = 91;
  /** RegularExpression Id. */
  int Stack = 92;
  /** RegularExpression Id. */
  int Queue = 93;
  /** RegularExpression Id. */
  int Retorno = 94;
  /** RegularExpression Id. */
  int Libreria = 95;
  /** RegularExpression Id. */
  int OperadorNew = 96;
  /** RegularExpression Id. */
  int Mas = 97;
  /** RegularExpression Id. */
  int Menos = 98;
  /** RegularExpression Id. */
  int Incremento = 99;
  /** RegularExpression Id. */
  int Decremento = 100;
  /** RegularExpression Id. */
  int Multiplicacion = 101;
  /** RegularExpression Id. */
  int Divison = 102;
  /** RegularExpression Id. */
  int Modulo = 103;
  /** RegularExpression Id. */
  int OpLogicoBoolUnitario = 104;
  /** RegularExpression Id. */
  int OrLogico = 105;
  /** RegularExpression Id. */
  int AndLogico = 106;
  /** RegularExpression Id. */
  int ExclusivoOrLogico = 107;
  /** RegularExpression Id. */
  int AND = 108;
  /** RegularExpression Id. */
  int OR = 109;
  /** RegularExpression Id. */
  int AndCondicional = 110;
  /** RegularExpression Id. */
  int OrCondicional = 111;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<Letra>",
    "<Numero>",
    "<Pregunta>",
    "<Entonces>",
    "<ParenIzq>",
    "<ParenDer>",
    "<Comilla>",
    "<Apost>",
    "<Comillas>",
    "<Char>",
    "<Int>",
    "<Float>",
    "<Double>",
    "<String>",
    "<Bool>",
    "<Var>",
    "<Byte>",
    "<Long>",
    "<Short>",
    "<Ulong>",
    "<Uint>",
    "<Sbyte>",
    "<Ushort>",
    "<Nchar>",
    "<Varchar>",
    "<DATE>",
    "<DATETIME>",
    "<Numeric>",
    "<NVARCHAR>",
    "<Bit>",
    "<TipoDato>",
    "<LlaveIzq>",
    "<LlaveDer>",
    "<PuntoYComa>",
    "<IgualIgual>",
    "<MenorQue>",
    "<MayorQue>",
    "<DiferenteDe>",
    "<MenorIgual>",
    "<MayorIgual>",
    "<AccesoMiembro>",
    "<Sustitucion>",
    "<Public>",
    "<Static>",
    "<Private>",
    "<TipoAcceso>",
    "<Do>",
    "<For>",
    "<Foreach>",
    "<While>",
    "<SelectivaMultiple>",
    "<Else>",
    "<Finally>",
    "<Default>",
    "<Asignar>",
    "<Case>",
    "<Metodo>",
    "<ClaseConsole>",
    "<Sobrecargar>",
    "<Concat>",
    "<Length>",
    "<Write>",
    "<WriteLine>",
    "<Delete>",
    "<Include>",
    "<Substring>",
    "<ToChar>",
    "<ToUpper>",
    "<ToLower>",
    "<ToString>",
    "<Next>",
    "<AVG>",
    "<Count>",
    "<Max>",
    "<Min>",
    "<Sum>",
    "<Estructura>",
    "<CapExcepcion>",
    "<Namespace>",
    "<Intenta>",
    "<Romper>",
    "<Base>",
    "<Checked>",
    "<BackColor>",
    "<Font>",
    "<Text>",
    "<Enabled>",
    "<TextAling>",
    "<True>",
    "<False>",
    "<List>",
    "<Stack>",
    "<Queue>",
    "<Retorno>",
    "<Libreria>",
    "<OperadorNew>",
    "<Mas>",
    "<Menos>",
    "<Incremento>",
    "<Decremento>",
    "<Multiplicacion>",
    "<Divison>",
    "<Modulo>",
    "<OpLogicoBoolUnitario>",
    "<OrLogico>",
    "<AndLogico>",
    "<ExclusivoOrLogico>",
    "<AND>",
    "<OR>",
    "<AndCondicional>",
    "<OrCondicional>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
