/* Generated By:JavaCC: Do not edit this line. compConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface compConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ComentC = 2;
  /** RegularExpression Id. */
  int ComentSQLInicio = 3;
  /** RegularExpression Id. */
  int ComentSQLFin = 4;
  /** RegularExpression Id. */
  int ComentHTML = 5;
  /** RegularExpression Id. */
  int ComentPy = 6;
  /** RegularExpression Id. */
  int Comentario = 7;
  /** RegularExpression Id. */
  int Pregunta = 8;
  /** RegularExpression Id. */
  int Entonces = 9;
  /** RegularExpression Id. */
  int ParenIzq = 10;
  /** RegularExpression Id. */
  int ParenDer = 11;
  /** RegularExpression Id. */
  int CorIzq = 12;
  /** RegularExpression Id. */
  int CorDer = 13;
  /** RegularExpression Id. */
  int Comilla = 14;
  /** RegularExpression Id. */
  int Apost = 15;
  /** RegularExpression Id. */
  int Comillas = 16;
  /** RegularExpression Id. */
  int Char = 17;
  /** RegularExpression Id. */
  int Nchar = 18;
  /** RegularExpression Id. */
  int String = 19;
  /** RegularExpression Id. */
  int Varchar = 20;
  /** RegularExpression Id. */
  int Var = 21;
  /** RegularExpression Id. */
  int DATE = 22;
  /** RegularExpression Id. */
  int DATETIME = 23;
  /** RegularExpression Id. */
  int Numeric = 24;
  /** RegularExpression Id. */
  int NVARCHAR = 25;
  /** RegularExpression Id. */
  int Bit = 26;
  /** RegularExpression Id. */
  int Bool = 27;
  /** RegularExpression Id. */
  int Money = 28;
  /** RegularExpression Id. */
  int Str = 29;
  /** RegularExpression Id. */
  int Int = 30;
  /** RegularExpression Id. */
  int Float = 31;
  /** RegularExpression Id. */
  int Double = 32;
  /** RegularExpression Id. */
  int Byte = 33;
  /** RegularExpression Id. */
  int Long = 34;
  /** RegularExpression Id. */
  int Short = 35;
  /** RegularExpression Id. */
  int Ulong = 36;
  /** RegularExpression Id. */
  int UINT = 37;
  /** RegularExpression Id. */
  int Sbyte = 38;
  /** RegularExpression Id. */
  int Ushort = 39;
  /** RegularExpression Id. */
  int TipoDatoNumerico = 40;
  /** RegularExpression Id. */
  int TipoDatoNoNumerico = 41;
  /** RegularExpression Id. */
  int LlaveIzq = 42;
  /** RegularExpression Id. */
  int LlaveDer = 43;
  /** RegularExpression Id. */
  int PuntoYComa = 44;
  /** RegularExpression Id. */
  int Gbajo = 45;
  /** RegularExpression Id. */
  int Coma = 46;
  /** RegularExpression Id. */
  int Puntuacion = 47;
  /** RegularExpression Id. */
  int IgualIgual = 48;
  /** RegularExpression Id. */
  int MenorQue = 49;
  /** RegularExpression Id. */
  int MayorQue = 50;
  /** RegularExpression Id. */
  int DiferenteDe = 51;
  /** RegularExpression Id. */
  int MenorIgual = 52;
  /** RegularExpression Id. */
  int MayorIgual = 53;
  /** RegularExpression Id. */
  int Comparador = 54;
  /** RegularExpression Id. */
  int AccesoMiembro = 55;
  /** RegularExpression Id. */
  int In = 56;
  /** RegularExpression Id. */
  int Clase = 57;
  /** RegularExpression Id. */
  int Arroba = 58;
  /** RegularExpression Id. */
  int SignoDinero = 59;
  /** RegularExpression Id. */
  int Sustitucion = 60;
  /** RegularExpression Id. */
  int Public = 61;
  /** RegularExpression Id. */
  int Protected = 62;
  /** RegularExpression Id. */
  int Private = 63;
  /** RegularExpression Id. */
  int Internal = 64;
  /** RegularExpression Id. */
  int TipoAcceso = 65;
  /** RegularExpression Id. */
  int Do = 66;
  /** RegularExpression Id. */
  int For = 67;
  /** RegularExpression Id. */
  int Foreach = 68;
  /** RegularExpression Id. */
  int While = 69;
  /** RegularExpression Id. */
  int Ciclo = 70;
  /** RegularExpression Id. */
  int SelectivaMultiple = 71;
  /** RegularExpression Id. */
  int Else = 72;
  /** RegularExpression Id. */
  int Finally = 73;
  /** RegularExpression Id. */
  int Default = 74;
  /** RegularExpression Id. */
  int Defecto = 75;
  /** RegularExpression Id. */
  int Asignar = 76;
  /** RegularExpression Id. */
  int Case = 77;
  /** RegularExpression Id. */
  int Metodo = 78;
  /** RegularExpression Id. */
  int ClaseConsole = 79;
  /** RegularExpression Id. */
  int Sobrecargar = 80;
  /** RegularExpression Id. */
  int Concat = 81;
  /** RegularExpression Id. */
  int Concat_Ws = 82;
  /** RegularExpression Id. */
  int Length = 83;
  /** RegularExpression Id. */
  int Write = 84;
  /** RegularExpression Id. */
  int WriteLine = 85;
  /** RegularExpression Id. */
  int Read = 86;
  /** RegularExpression Id. */
  int ReadLine = 87;
  /** RegularExpression Id. */
  int ReadKey = 88;
  /** RegularExpression Id. */
  int Ascii = 89;
  /** RegularExpression Id. */
  int Clear = 90;
  /** RegularExpression Id. */
  int Delete = 91;
  /** RegularExpression Id. */
  int Include = 92;
  /** RegularExpression Id. */
  int Substring = 93;
  /** RegularExpression Id. */
  int ToChar = 94;
  /** RegularExpression Id. */
  int Upper = 95;
  /** RegularExpression Id. */
  int ToUpper = 96;
  /** RegularExpression Id. */
  int Lower = 97;
  /** RegularExpression Id. */
  int ToLower = 98;
  /** RegularExpression Id. */
  int ToString = 99;
  /** RegularExpression Id. */
  int Next = 100;
  /** RegularExpression Id. */
  int Replace = 101;
  /** RegularExpression Id. */
  int Len = 102;
  /** RegularExpression Id. */
  int Imprimir = 103;
  /** RegularExpression Id. */
  int Reverse = 104;
  /** RegularExpression Id. */
  int As = 105;
  /** RegularExpression Id. */
  int EchoPhp = 106;
  /** RegularExpression Id. */
  int Format = 107;
  /** RegularExpression Id. */
  int FuncionString = 108;
  /** RegularExpression Id. */
  int AVG = 109;
  /** RegularExpression Id. */
  int Count = 110;
  /** RegularExpression Id. */
  int Max = 111;
  /** RegularExpression Id. */
  int Min = 112;
  /** RegularExpression Id. */
  int Sum = 113;
  /** RegularExpression Id. */
  int FuncionAgregar = 114;
  /** RegularExpression Id. */
  int DateDiff = 115;
  /** RegularExpression Id. */
  int DateAdd = 116;
  /** RegularExpression Id. */
  int DateName = 117;
  /** RegularExpression Id. */
  int Day = 118;
  /** RegularExpression Id. */
  int GetDate = 119;
  /** RegularExpression Id. */
  int Month = 120;
  /** RegularExpression Id. */
  int Year = 121;
  /** RegularExpression Id. */
  int FuncionDate = 122;
  /** RegularExpression Id. */
  int Abs = 123;
  /** RegularExpression Id. */
  int Acos = 124;
  /** RegularExpression Id. */
  int Asin = 125;
  /** RegularExpression Id. */
  int Atan = 126;
  /** RegularExpression Id. */
  int Cos = 127;
  /** RegularExpression Id. */
  int Cot = 128;
  /** RegularExpression Id. */
  int Floor = 129;
  /** RegularExpression Id. */
  int Log = 130;
  /** RegularExpression Id. */
  int LogDiez = 131;
  /** RegularExpression Id. */
  int Pi = 132;
  /** RegularExpression Id. */
  int Power = 133;
  /** RegularExpression Id. */
  int Radians = 134;
  /** RegularExpression Id. */
  int Round = 135;
  /** RegularExpression Id. */
  int Sin = 136;
  /** RegularExpression Id. */
  int Sqrt = 137;
  /** RegularExpression Id. */
  int Square = 138;
  /** RegularExpression Id. */
  int Tan = 139;
  /** RegularExpression Id. */
  int FuncionMath = 140;
  /** RegularExpression Id. */
  int Parse = 141;
  /** RegularExpression Id. */
  int Try_Cast = 142;
  /** RegularExpression Id. */
  int Try_Convert = 143;
  /** RegularExpression Id. */
  int Try_Parse = 144;
  /** RegularExpression Id. */
  int FuncionConvert = 145;
  /** RegularExpression Id. */
  int Choose = 146;
  /** RegularExpression Id. */
  int Greatest = 147;
  /** RegularExpression Id. */
  int Iif = 148;
  /** RegularExpression Id. */
  int Least = 149;
  /** RegularExpression Id. */
  int FuncionLogica = 150;
  /** RegularExpression Id. */
  int First_Value = 151;
  /** RegularExpression Id. */
  int Last_Value = 152;
  /** RegularExpression Id. */
  int Lag = 153;
  /** RegularExpression Id. */
  int Lead = 154;
  /** RegularExpression Id. */
  int FuncionAnalitic = 155;
  /** RegularExpression Id. */
  int Estructura = 156;
  /** RegularExpression Id. */
  int CapExcepcion = 157;
  /** RegularExpression Id. */
  int Namespace = 158;
  /** RegularExpression Id. */
  int Intenta = 159;
  /** RegularExpression Id. */
  int Romper = 160;
  /** RegularExpression Id. */
  int Base = 161;
  /** RegularExpression Id. */
  int Checked = 162;
  /** RegularExpression Id. */
  int BackColor = 163;
  /** RegularExpression Id. */
  int Font = 164;
  /** RegularExpression Id. */
  int Text = 165;
  /** RegularExpression Id. */
  int Enabled = 166;
  /** RegularExpression Id. */
  int TextAling = 167;
  /** RegularExpression Id. */
  int ReadOnly = 168;
  /** RegularExpression Id. */
  int Cursor = 169;
  /** RegularExpression Id. */
  int TabIndex = 170;
  /** RegularExpression Id. */
  int Visible = 171;
  /** RegularExpression Id. */
  int Locked = 172;
  /** RegularExpression Id. */
  int Size = 173;
  /** RegularExpression Id. */
  int Opacity = 174;
  /** RegularExpression Id. */
  int Icon = 175;
  /** RegularExpression Id. */
  int AcceptButton = 176;
  /** RegularExpression Id. */
  int CancelButton = 177;
  /** RegularExpression Id. */
  int DialogResult = 178;
  /** RegularExpression Id. */
  int Lang = 179;
  /** RegularExpression Id. */
  int Charset = 180;
  /** RegularExpression Id. */
  int Name = 181;
  /** RegularExpression Id. */
  int Content = 182;
  /** RegularExpression Id. */
  int Rel = 183;
  /** RegularExpression Id. */
  int Href = 184;
  /** RegularExpression Id. */
  int AtributosEtiqueta = 185;
  /** RegularExpression Id. */
  int Propiedad = 186;
  /** RegularExpression Id. */
  int True = 187;
  /** RegularExpression Id. */
  int False = 188;
  /** RegularExpression Id. */
  int ResultadoLogico = 189;
  /** RegularExpression Id. */
  int List = 190;
  /** RegularExpression Id. */
  int Stack = 191;
  /** RegularExpression Id. */
  int Queue = 192;
  /** RegularExpression Id. */
  int Lista = 193;
  /** RegularExpression Id. */
  int Retorno = 194;
  /** RegularExpression Id. */
  int Libreria = 195;
  /** RegularExpression Id. */
  int Colletions = 196;
  /** RegularExpression Id. */
  int Dynamic = 197;
  /** RegularExpression Id. */
  int IO = 198;
  /** RegularExpression Id. */
  int Linq = 199;
  /** RegularExpression Id. */
  int Resources = 200;
  /** RegularExpression Id. */
  int Security = 201;
  /** RegularExpression Id. */
  int Threading = 202;
  /** RegularExpression Id. */
  int Diagnostic = 203;
  /** RegularExpression Id. */
  int Drawing = 204;
  /** RegularExpression Id. */
  int TipoLibreria = 205;
  /** RegularExpression Id. */
  int Nulo = 206;
  /** RegularExpression Id. */
  int Not = 207;
  /** RegularExpression Id. */
  int Like = 208;
  /** RegularExpression Id. */
  int OperadorNew = 209;
  /** RegularExpression Id. */
  int Mas = 210;
  /** RegularExpression Id. */
  int Menos = 211;
  /** RegularExpression Id. */
  int OpAritmetico = 212;
  /** RegularExpression Id. */
  int Incremento = 213;
  /** RegularExpression Id. */
  int Decremento = 214;
  /** RegularExpression Id. */
  int OpAritmeticoUnitario = 215;
  /** RegularExpression Id. */
  int Multiplicacion = 216;
  /** RegularExpression Id. */
  int Divison = 217;
  /** RegularExpression Id. */
  int Modulo = 218;
  /** RegularExpression Id. */
  int OpAritmeticoBinario = 219;
  /** RegularExpression Id. */
  int OpLogicoBoolUnitario = 220;
  /** RegularExpression Id. */
  int OrLogico = 221;
  /** RegularExpression Id. */
  int AndLogico = 222;
  /** RegularExpression Id. */
  int ExclusivoOrLogico = 223;
  /** RegularExpression Id. */
  int AND = 224;
  /** RegularExpression Id. */
  int OR = 225;
  /** RegularExpression Id. */
  int OpLogicoBoolBinario = 226;
  /** RegularExpression Id. */
  int AndCondicional = 227;
  /** RegularExpression Id. */
  int OrCondicional = 228;
  /** RegularExpression Id. */
  int OpLogicoBoolBinarioCondicional = 229;
  /** RegularExpression Id. */
  int Select = 230;
  /** RegularExpression Id. */
  int From = 231;
  /** RegularExpression Id. */
  int Where = 232;
  /** RegularExpression Id. */
  int Consulta = 233;
  /** RegularExpression Id. */
  int GroupBy = 234;
  /** RegularExpression Id. */
  int Having = 235;
  /** RegularExpression Id. */
  int OrderBy = 236;
  /** RegularExpression Id. */
  int Over = 237;
  /** RegularExpression Id. */
  int TipoSelect = 238;
  /** RegularExpression Id. */
  int Inner = 239;
  /** RegularExpression Id. */
  int Join = 240;
  /** RegularExpression Id. */
  int Left = 241;
  /** RegularExpression Id. */
  int Outer = 242;
  /** RegularExpression Id. */
  int Right = 243;
  /** RegularExpression Id. */
  int Full = 244;
  /** RegularExpression Id. */
  int Cross = 245;
  /** RegularExpression Id. */
  int Apply = 246;
  /** RegularExpression Id. */
  int Pivot = 247;
  /** RegularExpression Id. */
  int Unpivot = 248;
  /** RegularExpression Id. */
  int TipoFrom = 249;
  /** RegularExpression Id. */
  int TipoWhere = 250;
  /** RegularExpression Id. */
  int BaseDatos = 251;
  /** RegularExpression Id. */
  int Procedimiento = 252;
  /** RegularExpression Id. */
  int Table = 253;
  /** RegularExpression Id. */
  int User = 254;
  /** RegularExpression Id. */
  int View = 255;
  /** RegularExpression Id. */
  int Function = 256;
  /** RegularExpression Id. */
  int TipoCreate = 257;
  /** RegularExpression Id. */
  int Add = 258;
  /** RegularExpression Id. */
  int DentroDe = 259;
  /** RegularExpression Id. */
  int Valores = 260;
  /** RegularExpression Id. */
  int Ejecutar = 261;
  /** RegularExpression Id. */
  int Alter = 262;
  /** RegularExpression Id. */
  int Create = 263;
  /** RegularExpression Id. */
  int Drop = 264;
  /** RegularExpression Id. */
  int Set = 265;
  /** RegularExpression Id. */
  int Use = 266;
  /** RegularExpression Id. */
  int Declaracion = 267;
  /** RegularExpression Id. */
  int Agregar = 268;
  /** RegularExpression Id. */
  int Check = 269;
  /** RegularExpression Id. */
  int Constraint = 270;
  /** RegularExpression Id. */
  int Llave = 271;
  /** RegularExpression Id. */
  int Primaria = 272;
  /** RegularExpression Id. */
  int Foranea = 273;
  /** RegularExpression Id. */
  int TipoLlave = 274;
  /** RegularExpression Id. */
  int Referencia = 275;
  /** RegularExpression Id. */
  int Unique = 276;
  /** RegularExpression Id. */
  int Insertar = 277;
  /** RegularExpression Id. */
  int Doctype = 278;
  /** RegularExpression Id. */
  int Body = 279;
  /** RegularExpression Id. */
  int Br = 280;
  /** RegularExpression Id. */
  int Button = 281;
  /** RegularExpression Id. */
  int Center = 282;
  /** RegularExpression Id. */
  int Col = 283;
  /** RegularExpression Id. */
  int Footer = 284;
  /** RegularExpression Id. */
  int Frame = 285;
  /** RegularExpression Id. */
  int H1 = 286;
  /** RegularExpression Id. */
  int H2 = 287;
  /** RegularExpression Id. */
  int H3 = 288;
  /** RegularExpression Id. */
  int H4 = 289;
  /** RegularExpression Id. */
  int H5 = 290;
  /** RegularExpression Id. */
  int H6 = 291;
  /** RegularExpression Id. */
  int Head = 292;
  /** RegularExpression Id. */
  int Header = 293;
  /** RegularExpression Id. */
  int Ht = 294;
  /** RegularExpression Id. */
  int Html = 295;
  /** RegularExpression Id. */
  int Img = 296;
  /** RegularExpression Id. */
  int Input = 297;
  /** RegularExpression Id. */
  int Label = 298;
  /** RegularExpression Id. */
  int Meta = 299;
  /** RegularExpression Id. */
  int Title = 300;
  /** RegularExpression Id. */
  int Etiqueta = 301;
  /** RegularExpression Id. */
  int Estatico = 302;
  /** RegularExpression Id. */
  int Main = 303;
  /** RegularExpression Id. */
  int Args = 304;
  /** RegularExpression Id. */
  int EventsArgs = 305;
  /** RegularExpression Id. */
  int Object = 306;
  /** RegularExpression Id. */
  int Sender = 307;
  /** RegularExpression Id. */
  int TerminarEtiqueta = 308;
  /** RegularExpression Id. */
  int Herencia = 309;
  /** RegularExpression Id. */
  int On = 310;
  /** RegularExpression Id. */
  int Dbo = 311;
  /** RegularExpression Id. */
  int Virgulilla = 312;
  /** RegularExpression Id. */
  int OpLogicoBoolUnitarioAbierto = 313;
  /** RegularExpression Id. */
  int Excepcion = 314;
  /** RegularExpression Id. */
  int Go = 315;
  /** RegularExpression Id. */
  int Letra = 316;
  /** RegularExpression Id. */
  int Letras = 317;
  /** RegularExpression Id. */
  int NumeroDecimal = 318;
  /** RegularExpression Id. */
  int Numero = 319;
  /** RegularExpression Id. */
  int Numeros = 320;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 321;
  /** RegularExpression Id. */
  int SQLBegin = 322;
  /** RegularExpression Id. */
  int SQLEnd = 323;
  /** RegularExpression Id. */
  int Login = 324;
  /** RegularExpression Id. */
  int Caracteres = 325;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<ComentC>",
    "<ComentSQLInicio>",
    "<ComentSQLFin>",
    "<ComentHTML>",
    "<ComentPy>",
    "<Comentario>",
    "<Pregunta>",
    "<Entonces>",
    "<ParenIzq>",
    "<ParenDer>",
    "<CorIzq>",
    "<CorDer>",
    "<Comilla>",
    "<Apost>",
    "<Comillas>",
    "<Char>",
    "<Nchar>",
    "<String>",
    "<Varchar>",
    "<Var>",
    "<DATE>",
    "<DATETIME>",
    "<Numeric>",
    "<NVARCHAR>",
    "<Bit>",
    "<Bool>",
    "<Money>",
    "<Str>",
    "<Int>",
    "<Float>",
    "<Double>",
    "<Byte>",
    "<Long>",
    "<Short>",
    "<Ulong>",
    "<UINT>",
    "<Sbyte>",
    "<Ushort>",
    "<TipoDatoNumerico>",
    "<TipoDatoNoNumerico>",
    "<LlaveIzq>",
    "<LlaveDer>",
    "<PuntoYComa>",
    "<Gbajo>",
    "<Coma>",
    "<Puntuacion>",
    "<IgualIgual>",
    "<MenorQue>",
    "<MayorQue>",
    "<DiferenteDe>",
    "<MenorIgual>",
    "<MayorIgual>",
    "<Comparador>",
    "<AccesoMiembro>",
    "\"in\"",
    "\"class\"",
    "<Arroba>",
    "<SignoDinero>",
    "<Sustitucion>",
    "<Public>",
    "<Protected>",
    "<Private>",
    "<Internal>",
    "<TipoAcceso>",
    "<Do>",
    "<For>",
    "<Foreach>",
    "<While>",
    "<Ciclo>",
    "<SelectivaMultiple>",
    "<Else>",
    "<Finally>",
    "<Default>",
    "<Defecto>",
    "<Asignar>",
    "<Case>",
    "<Metodo>",
    "<ClaseConsole>",
    "<Sobrecargar>",
    "<Concat>",
    "<Concat_Ws>",
    "<Length>",
    "<Write>",
    "<WriteLine>",
    "<Read>",
    "<ReadLine>",
    "<ReadKey>",
    "<Ascii>",
    "<Clear>",
    "<Delete>",
    "<Include>",
    "<Substring>",
    "<ToChar>",
    "<Upper>",
    "<ToUpper>",
    "<Lower>",
    "<ToLower>",
    "<ToString>",
    "<Next>",
    "<Replace>",
    "<Len>",
    "<Imprimir>",
    "<Reverse>",
    "<As>",
    "<EchoPhp>",
    "<Format>",
    "<FuncionString>",
    "<AVG>",
    "<Count>",
    "<Max>",
    "<Min>",
    "<Sum>",
    "<FuncionAgregar>",
    "<DateDiff>",
    "<DateAdd>",
    "<DateName>",
    "<Day>",
    "<GetDate>",
    "<Month>",
    "<Year>",
    "<FuncionDate>",
    "<Abs>",
    "<Acos>",
    "<Asin>",
    "<Atan>",
    "<Cos>",
    "<Cot>",
    "<Floor>",
    "<Log>",
    "<LogDiez>",
    "<Pi>",
    "<Power>",
    "<Radians>",
    "<Round>",
    "<Sin>",
    "<Sqrt>",
    "<Square>",
    "<Tan>",
    "<FuncionMath>",
    "<Parse>",
    "<Try_Cast>",
    "<Try_Convert>",
    "<Try_Parse>",
    "<FuncionConvert>",
    "<Choose>",
    "<Greatest>",
    "<Iif>",
    "<Least>",
    "<FuncionLogica>",
    "<First_Value>",
    "<Last_Value>",
    "<Lag>",
    "<Lead>",
    "<FuncionAnalitic>",
    "<Estructura>",
    "<CapExcepcion>",
    "<Namespace>",
    "<Intenta>",
    "<Romper>",
    "<Base>",
    "<Checked>",
    "<BackColor>",
    "<Font>",
    "<Text>",
    "<Enabled>",
    "<TextAling>",
    "<ReadOnly>",
    "<Cursor>",
    "<TabIndex>",
    "<Visible>",
    "<Locked>",
    "<Size>",
    "<Opacity>",
    "<Icon>",
    "<AcceptButton>",
    "<CancelButton>",
    "<DialogResult>",
    "<Lang>",
    "<Charset>",
    "<Name>",
    "<Content>",
    "<Rel>",
    "<Href>",
    "<AtributosEtiqueta>",
    "<Propiedad>",
    "<True>",
    "<False>",
    "<ResultadoLogico>",
    "<List>",
    "<Stack>",
    "<Queue>",
    "<Lista>",
    "<Retorno>",
    "<Libreria>",
    "<Colletions>",
    "<Dynamic>",
    "<IO>",
    "<Linq>",
    "<Resources>",
    "<Security>",
    "<Threading>",
    "<Diagnostic>",
    "<Drawing>",
    "<TipoLibreria>",
    "<Nulo>",
    "<Not>",
    "<Like>",
    "<OperadorNew>",
    "<Mas>",
    "<Menos>",
    "<OpAritmetico>",
    "<Incremento>",
    "<Decremento>",
    "<OpAritmeticoUnitario>",
    "<Multiplicacion>",
    "<Divison>",
    "<Modulo>",
    "<OpAritmeticoBinario>",
    "<OpLogicoBoolUnitario>",
    "<OrLogico>",
    "<AndLogico>",
    "<ExclusivoOrLogico>",
    "<AND>",
    "<OR>",
    "<OpLogicoBoolBinario>",
    "<AndCondicional>",
    "<OrCondicional>",
    "<OpLogicoBoolBinarioCondicional>",
    "<Select>",
    "<From>",
    "<Where>",
    "<Consulta>",
    "<GroupBy>",
    "<Having>",
    "<OrderBy>",
    "<Over>",
    "<TipoSelect>",
    "<Inner>",
    "<Join>",
    "<Left>",
    "<Outer>",
    "<Right>",
    "<Full>",
    "<Cross>",
    "<Apply>",
    "<Pivot>",
    "<Unpivot>",
    "<TipoFrom>",
    "<TipoWhere>",
    "<BaseDatos>",
    "<Procedimiento>",
    "<Table>",
    "<User>",
    "<View>",
    "<Function>",
    "<TipoCreate>",
    "<Add>",
    "<DentroDe>",
    "<Valores>",
    "<Ejecutar>",
    "<Alter>",
    "<Create>",
    "<Drop>",
    "<Set>",
    "<Use>",
    "<Declaracion>",
    "<Agregar>",
    "<Check>",
    "<Constraint>",
    "<Llave>",
    "<Primaria>",
    "<Foranea>",
    "<TipoLlave>",
    "<Referencia>",
    "<Unique>",
    "<Insertar>",
    "<Doctype>",
    "<Body>",
    "<Br>",
    "<Button>",
    "<Center>",
    "<Col>",
    "<Footer>",
    "<Frame>",
    "<H1>",
    "<H2>",
    "<H3>",
    "<H4>",
    "<H5>",
    "<H6>",
    "<Head>",
    "<Header>",
    "<Ht>",
    "<Html>",
    "<Img>",
    "<Input>",
    "<Label>",
    "<Meta>",
    "<Title>",
    "<Etiqueta>",
    "<Estatico>",
    "<Main>",
    "<Args>",
    "<EventsArgs>",
    "<Object>",
    "<Sender>",
    "<TerminarEtiqueta>",
    "<Herencia>",
    "<On>",
    "<Dbo>",
    "<Virgulilla>",
    "\"\\u00c2\\u00a1\"",
    "\"Exception\"",
    "<Go>",
    "<Letra>",
    "<Letras>",
    "<NumeroDecimal>",
    "<Numero>",
    "<Numeros>",
    "<IDENTIFICADOR>",
    "<SQLBegin>",
    "<SQLEnd>",
    "<Login>",
    "<Caracteres>",
  };

}
