/* Generated By:JavaCC: Do not edit this line. compTokenManager.java */

/** Token Manager. */
public class compTokenManager implements compConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0, long active1, long active2)
{
   switch (pos)
   {
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0, long active1, long active2)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1, active2), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 13:
         jjmatchedKind = 126;
         return jjMoveStringLiteralDfa1_0(0x8000000000000000L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, 0L, active1, 0L);
      return 1;
   }
   switch(curChar)
   {
      case 10:
         if ((active1 & 0x8000000000000000L) != 0L)
            return jjStopAtPos(1, 127);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, 0L, active1, 0L);
}
static private int jjMoveNfa_0(int startState, int curPos)
{
   //int[] nextStates; // not used
   int startsAt = 0;
   jjnewStateCnt = 368;
   int i = 1;
   jjstateSet[0] = startState;
   //int j; // not used
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x842000000000L & l) != 0L)
                  {
                     if (kind > 113)
                        kind = 113;
                  }
                  else if ((0x280000000000L & l) != 0L)
                  {
                     if (kind > 106)
                        kind = 106;
                  }
                  else if ((0x5000000000000000L & l) != 0L)
                  {
                     if (kind > 41)
                        kind = 41;
                  }
                  else if ((0x8400000000L & l) != 0L)
                  {
                     if (kind > 9)
                        kind = 9;
                  }
                  else if (curChar == 33)
                  {
                     if (kind > 114)
                        kind = 114;
                     jjCheckNAdd(26);
                  }
                  else if (curChar == 61)
                  {
                     if (kind > 58)
                        kind = 58;
                     jjCheckNAdd(26);
                  }
                  else if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 105;
                  else if (curChar == 46)
                  {
                     if (kind > 42)
                        kind = 42;
                  }
                  else if (curChar == 59)
                  {
                     if (kind > 34)
                        kind = 34;
                  }
                  else if (curChar == 41)
                  {
                     if (kind > 6)
                        kind = 6;
                  }
                  else if (curChar == 40)
                  {
                     if (kind > 5)
                        kind = 5;
                  }
                  if (curChar == 38)
                  {
                     if (kind > 120)
                        kind = 120;
                  }
                  else if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 99;
                  else if (curChar == 43)
                     jjstateSet[jjnewStateCnt++] = 97;
                  else if (curChar == 62)
                     jjCheckNAdd(26);
                  else if (curChar == 60)
                     jjCheckNAdd(26);
                  break;
               case 2:
                  if (curChar == 40)
                     kind = 5;
                  break;
               case 3:
                  if (curChar == 41)
                     kind = 6;
                  break;
               case 4:
                  if ((0x8400000000L & l) != 0L)
                     kind = 9;
                  break;
               case 23:
                  if (curChar == 59)
                     kind = 34;
                  break;
               case 24:
                  if ((0x5000000000000000L & l) != 0L && kind > 41)
                     kind = 41;
                  break;
               case 25:
                  if (curChar == 60)
                     jjCheckNAdd(26);
                  break;
               case 26:
                  if (curChar == 61 && kind > 41)
                     kind = 41;
                  break;
               case 27:
                  if (curChar == 62)
                     jjCheckNAdd(26);
                  break;
               case 28:
                  if (curChar == 46)
                     kind = 42;
                  break;
               case 95:
                  if ((0x280000000000L & l) != 0L && kind > 106)
                     kind = 106;
                  break;
               case 96:
                  if (curChar == 43)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 97:
                  if (curChar == 43 && kind > 109)
                     kind = 109;
                  break;
               case 98:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 99:
                  if (curChar == 45 && kind > 109)
                     kind = 109;
                  break;
               case 100:
                  if ((0x842000000000L & l) != 0L)
                     kind = 113;
                  break;
               case 101:
                  if (curChar == 38 && kind > 120)
                     kind = 120;
                  break;
               case 104:
                  if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 105:
                  if (curChar == 38 && kind > 123)
                     kind = 123;
                  break;
               case 218:
                  if (curChar != 61)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjCheckNAdd(26);
                  break;
               case 219:
                  if (curChar != 33)
                     break;
                  kind = 114;
                  jjCheckNAdd(26);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x200000002L & l) != 0L)
                     jjAddStates(0, 1);
                  else if ((0x4000000040L & l) != 0L)
                     jjAddStates(2, 3);
                  else if ((0x1000000010L & l) != 0L)
                     jjAddStates(4, 5);
                  else if ((0x400000004000L & l) != 0L)
                     jjAddStates(6, 8);
                  else if ((0x200000002000L & l) != 0L)
                     jjAddStates(9, 10);
                  else if ((0x8000000080000L & l) != 0L)
                     jjAddStates(11, 12);
                  else if ((0x800000008L & l) != 0L)
                     jjAddStates(13, 14);
                  else if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 103;
                  else if ((0x1000000040000000L & l) != 0L)
                  {
                     if (kind > 120)
                        kind = 120;
                  }
                  else if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 78;
                  else if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 20;
                  else if ((0x40000000400000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 13;
                  else if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 6;
                  else if (curChar == 117)
                     jjAddStates(15, 18);
                  else if (curChar == 76)
                     jjAddStates(19, 20);
                  else if (curChar == 112)
                     jjAddStates(21, 22);
                  else if (curChar == 87)
                     jjAddStates(23, 24);
                  else if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 87;
                  else if (curChar == 81)
                     jjstateSet[jjnewStateCnt++] = 82;
                  else if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 72;
                  else if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 36;
                  else if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 31;
                  else if (curChar == 64)
                  {
                     if (kind > 43)
                        kind = 43;
                  }
                  else if (curChar == 125)
                  {
                     if (kind > 33)
                        kind = 33;
                  }
                  else if (curChar == 123)
                  {
                     if (kind > 32)
                        kind = 32;
                  }
                  else if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 9;
                  if (curChar == 84)
                     jjAddStates(25, 30);
                  else if (curChar == 98)
                     jjAddStates(31, 34);
                  else if (curChar == 83)
                     jjAddStates(35, 36);
                  else if (curChar == 67)
                     jjAddStates(37, 38);
                  else if (curChar == 68)
                     jjAddStates(39, 40);
                  else if (curChar == 102)
                     jjAddStates(41, 43);
                  else if (curChar == 115)
                     jjAddStates(44, 49);
                  else if (curChar == 118)
                     jjAddStates(50, 51);
                  else if (curChar == 100)
                     jjAddStates(52, 53);
                  else if (curChar == 99)
                     jjAddStates(54, 56);
                  else if (curChar == 116)
                     jjAddStates(57, 58);
                  else if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 107;
                  else if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 93;
                  else if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 68;
                  else if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 59;
                  else if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 55;
                  else if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 48;
                  else if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 40;
                  else if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 1:
                  if (curChar == 102 && kind > 3)
                     kind = 3;
                  break;
               case 5:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 6:
                  if ((0x400000004000L & l) != 0L)
                     jjCheckNAdd(7);
                  break;
               case 7:
                  if ((0x10000000100000L & l) != 0L && kind > 31)
                     kind = 31;
                  break;
               case 8:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 9:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 10:
               case 224:
               case 323:
                  if (curChar == 110)
                     jjCheckNAdd(11);
                  break;
               case 11:
                  if (curChar == 103 && kind > 31)
                     kind = 31;
                  break;
               case 12:
                  if ((0x40000000400000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 13:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 14:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 15:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 16:
                  if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 17:
               case 159:
               case 171:
                  if ((0x200000002L & l) != 0L)
                     jjCheckNAdd(18);
                  break;
               case 18:
                  if ((0x4000000040000L & l) != 0L && kind > 31)
                     kind = 31;
                  break;
               case 19:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 20:
                  if ((0x20000000200L & l) != 0L)
                     jjCheckNAdd(7);
                  break;
               case 21:
                  if (curChar == 123)
                     kind = 32;
                  break;
               case 22:
                  if (curChar == 125)
                     kind = 33;
                  break;
               case 29:
                  if (curChar == 64)
                     kind = 43;
                  break;
               case 30:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 31:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 32:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 33:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 34:
                  if (curChar == 101 && kind > 52)
                     kind = 52;
                  break;
               case 35:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 36:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 37:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 38:
                  if (curChar == 101 && kind > 57)
                     kind = 57;
                  break;
               case 39:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 40:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 41:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 42:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 43:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 44:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 45:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 46:
                  if (curChar == 101 && kind > 62)
                     kind = 62;
                  break;
               case 47:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 48:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 49:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 50:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 51:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 52:
                  if (curChar == 100)
                     jjCheckNAdd(53);
                  break;
               case 53:
                  if (curChar == 101 && kind > 80)
                     kind = 80;
                  break;
               case 54:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 55:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 56:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 57:
                  if (curChar == 116 && kind > 80)
                     kind = 80;
                  break;
               case 58:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 59:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 60:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 61:
                  if (curChar == 107)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 62:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 63:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 64:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 65:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 66:
                  if (curChar == 114 && kind > 93)
                     kind = 93;
                  break;
               case 67:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 68:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 69:
                  if (curChar == 110)
                     jjCheckNAdd(70);
                  break;
               case 70:
                  if (curChar == 100 && kind > 93)
                     kind = 93;
                  break;
               case 71:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 72:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 73:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 74:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 75:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 76:
               case 283:
                  if (curChar == 101)
                     jjCheckNAdd(70);
                  break;
               case 77:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 78:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 79:
                  if ((0x20000000200000L & l) != 0L)
                     jjCheckNAdd(80);
                  break;
               case 80:
                  if ((0x2000000020L & l) != 0L && kind > 96)
                     kind = 96;
                  break;
               case 81:
                  if (curChar == 81)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 82:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 83:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 84:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 85:
                  if (curChar == 101 && kind > 100)
                     kind = 100;
                  break;
               case 86:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 87:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 88:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 89:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 90:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 91:
                  if (curChar == 110 && kind > 101)
                     kind = 101;
                  break;
               case 92:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 93:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 94:
                  if (curChar == 119 && kind > 103)
                     kind = 103;
                  break;
               case 101:
                  if ((0x1000000040000000L & l) != 0L && kind > 120)
                     kind = 120;
                  break;
               case 102:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 103:
                  if ((0x4000000040000L & l) != 0L && kind > 120)
                     kind = 120;
                  break;
               case 106:
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 107:
                  if (curChar == 124 && kind > 123)
                     kind = 123;
                  break;
               case 108:
                  if ((0x800000008L & l) != 0L)
                     jjAddStates(13, 14);
                  break;
               case 109:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 110:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 111;
                  break;
               case 111:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 112:
                  if ((0x200000002L & l) != 0L)
                     jjCheckNAdd(113);
                  break;
               case 113:
                  if ((0x10000000100000L & l) != 0L && kind > 80)
                     kind = 80;
                  break;
               case 114:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 115:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 116:
                  if ((0x400000004000L & l) != 0L)
                     jjCheckNAdd(113);
                  break;
               case 117:
                  if (curChar == 87)
                     jjAddStates(23, 24);
                  break;
               case 118:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 119:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 120:
               case 271:
                  if (curChar == 116)
                     jjCheckNAdd(53);
                  break;
               case 121:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 122:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 123:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 124;
                  break;
               case 124:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 125:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 126:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 127:
                  if (curChar == 110)
                     jjCheckNAdd(53);
                  break;
               case 128:
                  if ((0x8000000080000L & l) != 0L)
                     jjAddStates(11, 12);
                  break;
               case 129:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 130:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 131:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 132:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 133:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 134:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 135;
                  break;
               case 135:
                  if ((0x400000004000L & l) != 0L)
                     jjCheckNAdd(136);
                  break;
               case 136:
                  if ((0x8000000080L & l) != 0L && kind > 80)
                     kind = 80;
                  break;
               case 137:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 138;
                  break;
               case 138:
                  if ((0x200000002000L & l) != 0L && kind > 80)
                     kind = 80;
                  break;
               case 139:
                  if ((0x200000002000L & l) != 0L)
                     jjAddStates(9, 10);
                  break;
               case 140:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 141;
                  break;
               case 141:
                  if ((0x100000001000000L & l) != 0L && kind > 80)
                     kind = 80;
                  break;
               case 142:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 143;
                  break;
               case 143:
                  if ((0x400000004000L & l) != 0L && kind > 80)
                     kind = 80;
                  break;
               case 144:
                  if (curChar == 112)
                     jjAddStates(21, 22);
                  break;
               case 145:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 146;
                  break;
               case 146:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 147;
                  break;
               case 147:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 148;
                  break;
               case 148:
               case 235:
                  if (curChar == 105)
                     jjCheckNAdd(149);
                  break;
               case 149:
                  if (curChar == 99 && kind > 47)
                     kind = 47;
                  break;
               case 150:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 151:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 152;
                  break;
               case 152:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 153:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 154:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 155;
                  break;
               case 155:
                  if (curChar == 101 && kind > 47)
                     kind = 47;
                  break;
               case 156:
                  if ((0x400000004000L & l) != 0L)
                     jjAddStates(6, 8);
                  break;
               case 157:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 158:
                  if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 159;
                  break;
               case 160:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 161;
                  break;
               case 161:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 162:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 163;
                  break;
               case 163:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 164;
                  break;
               case 164:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 165;
                  break;
               case 165:
                  if ((0x800000008L & l) != 0L && kind > 31)
                     kind = 31;
                  break;
               case 166:
                  if ((0x40000000400000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 167;
                  break;
               case 167:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 168:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 169;
                  break;
               case 169:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 170;
                  break;
               case 170:
                  if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 171;
                  break;
               case 172:
                  if ((0x1000000010L & l) != 0L)
                     jjAddStates(4, 5);
                  break;
               case 173:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 174;
                  break;
               case 174:
                  if ((0x10000000100000L & l) != 0L)
                     jjCheckNAdd(175);
                  break;
               case 175:
                  if ((0x2000000020L & l) != 0L && kind > 31)
                     kind = 31;
                  break;
               case 176:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 177;
                  break;
               case 177:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 178;
                  break;
               case 178:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 179;
                  break;
               case 179:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 180;
                  break;
               case 180:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 181;
                  break;
               case 181:
                  if ((0x200000002000L & l) != 0L)
                     jjCheckNAdd(175);
                  break;
               case 182:
                  if (curChar == 116)
                     jjAddStates(57, 58);
                  break;
               case 183:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 184;
                  break;
               case 184:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 185;
                  break;
               case 185:
                  if (curChar == 110 && kind > 4)
                     kind = 4;
                  break;
               case 186:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 187;
                  break;
               case 187:
                  if (curChar == 121 && kind > 84)
                     kind = 84;
                  break;
               case 188:
                  if (curChar == 99)
                     jjAddStates(54, 56);
                  break;
               case 189:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 190;
                  break;
               case 190:
               case 214:
                  if (curChar == 97)
                     jjCheckNAdd(191);
                  break;
               case 191:
                  if (curChar == 114 && kind > 31)
                     kind = 31;
                  break;
               case 192:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 193;
                  break;
               case 193:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               case 194:
                  if (curChar == 101 && kind > 59)
                     kind = 59;
                  break;
               case 195:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 196;
                  break;
               case 196:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 197;
                  break;
               case 197:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 198;
                  break;
               case 198:
                  if (curChar == 104 && kind > 82)
                     kind = 82;
                  break;
               case 199:
                  if ((0x4000000040L & l) != 0L)
                     jjAddStates(2, 3);
                  break;
               case 200:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 201;
                  break;
               case 201:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 202;
                  break;
               case 202:
                  if ((0x200000002L & l) != 0L)
                     jjCheckNAdd(7);
                  break;
               case 203:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 204;
                  break;
               case 204:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 205;
                  break;
               case 205:
                  if ((0x8000000080000L & l) != 0L)
                     jjCheckNAdd(80);
                  break;
               case 206:
                  if (curChar == 100)
                     jjAddStates(52, 53);
                  break;
               case 207:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 208;
                  break;
               case 208:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 209;
                  break;
               case 209:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 210;
                  break;
               case 210:
                  if (curChar == 108)
                     jjCheckNAdd(211);
                  break;
               case 211:
                  if (curChar == 101 && kind > 31)
                     kind = 31;
                  break;
               case 212:
                  if (curChar == 111 && kind > 52)
                     kind = 52;
                  break;
               case 213:
                  if (curChar == 118)
                     jjAddStates(50, 51);
                  break;
               case 215:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 216;
                  break;
               case 216:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 217;
                  break;
               case 217:
                  if (curChar == 100 && kind > 60)
                     kind = 60;
                  break;
               case 220:
                  if (curChar == 115)
                     jjAddStates(44, 49);
                  break;
               case 221:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 222;
                  break;
               case 222:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 223;
                  break;
               case 223:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 224;
                  break;
               case 225:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 226;
                  break;
               case 226:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 227;
                  break;
               case 227:
               case 329:
                  if (curChar == 114)
                     jjCheckNAdd(228);
                  break;
               case 228:
                  if (curChar == 116 && kind > 31)
                     kind = 31;
                  break;
               case 229:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 230;
                  break;
               case 230:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 231;
                  break;
               case 231:
               case 312:
                  if (curChar == 116)
                     jjCheckNAdd(211);
                  break;
               case 232:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 233;
                  break;
               case 233:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 234;
                  break;
               case 234:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 235;
                  break;
               case 236:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 237;
                  break;
               case 237:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 238;
                  break;
               case 238:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 239;
                  break;
               case 239:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 240;
                  break;
               case 240:
                  if (curChar == 104 && kind > 53)
                     kind = 53;
                  break;
               case 241:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 242;
                  break;
               case 242:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 243;
                  break;
               case 243:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 244;
                  break;
               case 244:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 245;
                  break;
               case 245:
                  if (curChar == 116 && kind > 81)
                     kind = 81;
                  break;
               case 246:
                  if (curChar == 102)
                     jjAddStates(41, 43);
                  break;
               case 247:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 248;
                  break;
               case 248:
                  if (curChar == 114 && kind > 52)
                     kind = 52;
                  break;
               case 249:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 250;
                  break;
               case 250:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 251;
                  break;
               case 251:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 252;
                  break;
               case 252:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 253;
                  break;
               case 253:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 254;
                  break;
               case 254:
                  if (curChar == 104 && kind > 52)
                     kind = 52;
                  break;
               case 255:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 256;
                  break;
               case 256:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 257;
                  break;
               case 257:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 258;
                  break;
               case 258:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 259;
                  break;
               case 259:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 260;
                  break;
               case 260:
                  if (curChar == 121 && kind > 57)
                     kind = 57;
                  break;
               case 261:
                  if (curChar == 68)
                     jjAddStates(39, 40);
                  break;
               case 262:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 263;
                  break;
               case 263:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 264;
                  break;
               case 264:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 265;
                  break;
               case 265:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 266;
                  break;
               case 266:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 267;
                  break;
               case 267:
                  if (curChar == 100 && kind > 57)
                     kind = 57;
                  break;
               case 268:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 269;
                  break;
               case 269:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 270;
                  break;
               case 270:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 271;
                  break;
               case 272:
                  if (curChar == 67)
                     jjAddStates(37, 38);
                  break;
               case 273:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 274;
                  break;
               case 274:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 275;
                  break;
               case 275:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 276;
                  break;
               case 276:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 277;
                  break;
               case 277:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 278;
                  break;
               case 278:
                  if (curChar == 101 && kind > 61)
                     kind = 61;
                  break;
               case 279:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 280;
                  break;
               case 280:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 281;
                  break;
               case 281:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 282;
                  break;
               case 282:
                  if (curChar == 107)
                     jjstateSet[jjnewStateCnt++] = 283;
                  break;
               case 284:
                  if (curChar == 76)
                     jjAddStates(19, 20);
                  break;
               case 285:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 286;
                  break;
               case 286:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 287;
                  break;
               case 287:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 288;
                  break;
               case 288:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 289;
                  break;
               case 289:
                  if (curChar == 104 && kind > 80)
                     kind = 80;
                  break;
               case 290:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 291;
                  break;
               case 291:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 292;
                  break;
               case 292:
                  if (curChar == 116 && kind > 100)
                     kind = 100;
                  break;
               case 293:
                  if ((0x200000002L & l) != 0L)
                     jjAddStates(0, 1);
                  break;
               case 294:
                  if ((0x40000000400000L & l) != 0L)
                     jjCheckNAdd(136);
                  break;
               case 295:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 296;
                  break;
               case 296:
                  if ((0x1000000010L & l) != 0L && kind > 120)
                     kind = 120;
                  break;
               case 297:
                  if (curChar == 83)
                     jjAddStates(35, 36);
                  break;
               case 298:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 299;
                  break;
               case 299:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 300;
                  break;
               case 300:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 301;
                  break;
               case 301:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 302;
                  break;
               case 302:
                  if (curChar == 109 && kind > 83)
                     kind = 83;
                  break;
               case 303:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 304;
                  break;
               case 304:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 305;
                  break;
               case 305:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 306;
                  break;
               case 306:
                  if (curChar == 107 && kind > 100)
                     kind = 100;
                  break;
               case 307:
                  if (curChar == 98)
                     jjAddStates(31, 34);
                  break;
               case 308:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 309;
                  break;
               case 309:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 310;
                  break;
               case 310:
                  if (curChar == 108 && kind > 31)
                     kind = 31;
                  break;
               case 311:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 312;
                  break;
               case 313:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 314;
                  break;
               case 314:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 315;
                  break;
               case 315:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 316;
                  break;
               case 316:
                  if (curChar == 107 && kind > 85)
                     kind = 85;
                  break;
               case 317:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 318;
                  break;
               case 318:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 319;
                  break;
               case 319:
                  if (curChar == 101 && kind > 86)
                     kind = 86;
                  break;
               case 320:
                  if (curChar == 117)
                     jjAddStates(15, 18);
                  break;
               case 321:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 322;
                  break;
               case 322:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 323;
                  break;
               case 324:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 325;
                  break;
               case 325:
                  if (curChar == 110)
                     jjCheckNAdd(228);
                  break;
               case 326:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 327;
                  break;
               case 327:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 328;
                  break;
               case 328:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 329;
                  break;
               case 330:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 331;
                  break;
               case 331:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 332;
                  break;
               case 332:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 333;
                  break;
               case 333:
                  if (curChar == 103 && kind > 102)
                     kind = 102;
                  break;
               case 334:
                  if (curChar == 84)
                     jjAddStates(25, 30);
                  break;
               case 335:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 336;
                  break;
               case 336:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 337;
                  break;
               case 337:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 338;
                  break;
               case 338:
                  if (curChar == 97)
                     jjCheckNAdd(339);
                  break;
               case 339:
                  if (curChar == 114 && kind > 80)
                     kind = 80;
                  break;
               case 340:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 341;
                  break;
               case 341:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 342;
                  break;
               case 342:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 343;
                  break;
               case 343:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 344;
                  break;
               case 344:
               case 349:
                  if (curChar == 101)
                     jjCheckNAdd(339);
                  break;
               case 345:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 346;
                  break;
               case 346:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 347;
                  break;
               case 347:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 348;
                  break;
               case 348:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 349;
                  break;
               case 350:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 351;
                  break;
               case 351:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 352;
                  break;
               case 352:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 353;
                  break;
               case 353:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 354;
                  break;
               case 354:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 355;
                  break;
               case 355:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 356;
                  break;
               case 356:
                  if (curChar == 103 && kind > 80)
                     kind = 80;
                  break;
               case 357:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 358;
                  break;
               case 358:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 359;
                  break;
               case 359:
                  if (curChar == 84 && kind > 93)
                     kind = 93;
                  break;
               case 360:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 361;
                  break;
               case 361:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 362;
                  break;
               case 362:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 363;
                  break;
               case 363:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 364;
                  break;
               case 364:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 365;
                  break;
               case 365:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 366;
                  break;
               case 366:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 367;
                  break;
               case 367:
                  if (curChar == 110 && kind > 93)
                     kind = 93;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 368 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   294, 295, 200, 203, 173, 176, 157, 160, 166, 140, 142, 129, 137, 109, 114, 321, 
   324, 326, 330, 285, 290, 145, 150, 118, 121, 335, 340, 345, 350, 357, 360, 308, 
   311, 313, 317, 298, 303, 273, 279, 262, 268, 247, 249, 255, 221, 225, 229, 232, 
   236, 241, 214, 215, 207, 212, 189, 192, 195, 183, 186, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0x7e308e0780000279L, 0x90624f1207f0000L, 0x0L, 
};
static final long[] jjtoSkip = {
   0x0L, 0xf000000000000000L, 0x1L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[368];
static private final int[] jjstateSet = new int[736];
static StringBuffer image;
static int jjimageLen;
static int lengthOfMatch;
static protected char curChar;
/** Constructor. */
public compTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public compTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 368; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String tokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   tokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, tokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  //int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }
   image = null;
   jjimageLen = 0;

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100000600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         TokenLexicalActions(matchedToken);
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 3 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Pregunta");
         break;
      case 4 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Entonces");
         break;
      case 5 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("ParenIzq");
         break;
      case 6 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("ParenDer");
         break;
      case 9 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Comillas: " + image);
         break;
      case 31 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("TipoDato: " + image);
         break;
      case 32 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("LlaveIzq");
         break;
      case 33 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("LlaveDer");
         break;
      case 34 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("PuntoYComa");
         break;
      case 41 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        System.out.println("Comparador: " + image);
         break;
      case 42 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("AccesoMiembro");
         break;
      case 43 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Sustitucion");
         break;
      case 47 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("TipoDato: " + image);
         break;
      case 52 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Ciclo: " + image);
         break;
      case 53 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("SelectivaMultiple");
         break;
      case 57 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Defecto: " + image);
         break;
      case 58 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Asignar");
         break;
      case 59 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Case");
         break;
      case 60 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Metodo");
         break;
      case 61 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("ClaseConsole");
         break;
      case 62 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Sobrecargar");
         break;
      case 80 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Funcion: " + image);
         break;
      case 81 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Estructura");
         break;
      case 82 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("CapExcepci\u00c3\u00b3n");
         break;
      case 83 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Namespace");
         break;
      case 84 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Intenta");
         break;
      case 85 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Romper");
         break;
      case 86 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Base");
         break;
      case 93 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Propiedad: " + image);
         break;
      case 96 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("ResultadoLogico: " + image);
         break;
      case 100 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Lista: " + image);
         break;
      case 101 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Retorno");
         break;
      case 102 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("Libreria");
         break;
      case 103 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("OperadorNew");
         break;
      case 106 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("OpAritmetico: " + image);
         break;
      case 109 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("OpAritmeticoUnitario: " + image);
         break;
      case 113 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("OpAritmeticoBinario: " + image);
         break;
      case 114 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("OpLogicoBoolUnitario");
         break;
      case 120 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("OpLogicoBoolBinario: " + image);
         break;
      case 123 :
        if (image == null)
            image = new StringBuffer();
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                System.out.println("OpLogicoBoolBinarioCondicional: " + image);
         break;
      default : 
         break;
   }
}
static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
