/* comp.java */
/* Generated By:JavaCC: Do not edit this line. comp.java */
import java.util.*;
class comp implements compConstants {
        public static void main( String[] args )throws ParseException
        {
                try
                {
                comp Checker = new comp( System.in ) ;
                        Checker.Program();
                        System.out.println("\u005ctHabemus analizado todo.");
                }
                catch(ParseException e)
                {
                        System.err.print(e.getMessage());
                        System.out.println("\u005ctChecker ha terminado.");
                }
                catch(TokenMgrError e)
                {
                        System.err.print(e.getMessage());
                        System.out.println("\u005ctChecker ha terminado.");
                }
        }

/* || ========== || [ FINALIZA LEXICO ] || ========== || */

/* || ========== || [ INICIA SINTACTICO ] || ========== || */
  static final public 
void Program() throws ParseException {System.out.println("+==========================================+");
        System.out.println("|     Token      |=====|    Atributo       |");
        System.out.println("+==========================================+");
        boolean flag = true;
        int Tid;
        String Timage;
        List<String> ID = new ArrayList<String>();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case Pregunta:
      case TipoDato:
      case TipoAcceso:
      case Do:
      case Foreach:
      case While:
      case Metodo:
      case Intenta:
      case Declaracion:
      case Insertar:
      case Estatico:
      case Caracteres:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case Foreach:{
        SentenciaForeach();
System.out.println("  SentenciaForeach" + "   \u005ct\u005ct" +  "\u005ct\u005ct     ");
                flag=false;
        break;
        }
      case Do:{
        SentenciaDoWhile();
System.out.println("  SentenciaDoWhile" + "   \u005ct\u005ct" +  "\u005ct\u005ct     ");
                flag=false;
        break;
        }
      case While:{
        SentenciaWhile();
System.out.println("  SentenciaWhile" + "   \u005ct\u005ct" +  "\u005ct\u005ct     ");
                flag=false;
        break;
        }
      case Pregunta:{
        SentenciaIf();
System.out.println("  SentenciaIf" + "   \u005ct\u005ct" +  "\u005ct\u005ct     ");
                flag=false;
        break;
        }
      case TipoDato:{
        DeclaracionVariable();
System.out.println("  DeclaracionVariable" + "   \u005ct\u005ct" +  "\u005ct\u005ct     ");
                flag=false;
        break;
        }
      case Caracteres:{
        SentenciaLlamadaMetodo();
System.out.println("  SentenciaLlamadaMetodo" + "   \u005ct\u005ct" +  "\u005ct\u005ct     ");
                flag=false;
        break;
        }
      case TipoAcceso:
      case Metodo:
      case Estatico:{
        SentenciaMetodo();
System.out.println("  SentenciaMetodo" + "   \u005ct\u005ct" +  "\u005ct\u005ct     ");
                flag=false;
        break;
        }
      case Intenta:{
        SentenciaTryCatch();
System.out.println("  SentenciaTryCatch" + "   \u005ct\u005ct" +  "\u005ct\u005ct     ");
                flag=false;
        break;
        }
      case Declaracion:{
        SentenciaDeclaracion();
System.out.println("  SentenciaDeclaracion" + "   \u005ct\u005ct" +  "\u005ct\u005ct     ");
                flag=false;
        break;
        }
      case Insertar:{
        SentenciaInsertarEnTabla();
System.out.println("  SentenciaInsertarEnTabla" + "   \u005ct\u005ct" +  "\u005ct\u005ct     ");
                flag=false;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(0);
System.out.println("+===================================================+");
  }

/* || ============================== || [ INICIA COMPLEMENTOS ] || ============================== || */
  static final public 
void Condicion() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Numero:{
      label_2:
      while (true) {
        jj_consume_token(Numero);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case Numero:{
          ;
          break;
          }
        default:
          jj_la1[2] = jj_gen;
          break label_2;
        }
      }
      break;
      }
    case Caracteres:{
      jj_consume_token(Caracteres);
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(Comparador);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Numero:{
      label_3:
      while (true) {
        jj_consume_token(Numero);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case Numero:{
          ;
          break;
          }
        default:
          jj_la1[4] = jj_gen;
          break label_3;
        }
      }
      break;
      }
    case Caracteres:{
      jj_consume_token(Caracteres);
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void MasVariables() throws ParseException {
    jj_consume_token(Coma);
    jj_consume_token(Caracteres);
  }

  static final public void Parametro() throws ParseException {
    jj_consume_token(TipoDato);
    jj_consume_token(Caracteres);
  }

  static final public void InicioMetodo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TipoAcceso:{
      jj_consume_token(TipoAcceso);
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Estatico:{
      jj_consume_token(Estatico);
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      ;
    }
  }

  static final public void InicioDeclaracion() throws ParseException {
    jj_consume_token(Declaracion);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TipoCreate:{
      jj_consume_token(TipoCreate);
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      ;
    }
    jj_consume_token(Caracteres);
  }

  static final public void Texto() throws ParseException {
    jj_consume_token(Apost);
    jj_consume_token(Caracteres);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case Caracteres:{
        ;
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        break label_4;
      }
      jj_consume_token(Caracteres);
    }
    jj_consume_token(Apost);
  }

  static final public void MasValores() throws ParseException {
    jj_consume_token(Coma);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Apost:{
      Texto();
      break;
      }
    case Numero:{
      jj_consume_token(Numero);
      break;
      }
    case NumeroDecimal:{
      jj_consume_token(NumeroDecimal);
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void EstructuraMetodo() throws ParseException {
    jj_consume_token(Caracteres);
    jj_consume_token(ParenIzq);
    SentenciaDeclaracionParametro();
    jj_consume_token(ParenDer);
    jj_consume_token(LlaveIzq);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Retorno:{
      jj_consume_token(Retorno);
      jj_consume_token(Caracteres);
      jj_consume_token(PuntoYComa);
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    jj_consume_token(LlaveDer);
  }

  static final public void SentenciaDeclaracionParametro() throws ParseException {
    Parametro();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case Coma:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_5;
      }
      jj_consume_token(Coma);
      Parametro();
    }
  }

/*****************************************************************************************************************
void TodoElTexto():{}{
	( <Letras> | <Numeros> | <OpAritmeticoBinario> | <OpLogicoBoolUnitarioAbierto> | SentenciaIf())*
}
*****************************************************************************************************************/
/*
void TextosComentario():{}{
	<	TextoComentario: ~[]	>
}
*/

/* || ============================== || [ FINALIZA COMPLEMENTOS ] || ============================== || */

/* SentenciaForeach [Estructura #1] */
  static final public void SentenciaForeach() throws ParseException {
    jj_consume_token(Foreach);
    jj_consume_token(ParenIzq);
    jj_consume_token(TipoDato);
    jj_consume_token(Caracteres);
    jj_consume_token(In);
    jj_consume_token(Caracteres);
    jj_consume_token(ParenDer);
    jj_consume_token(LlaveIzq);
    jj_consume_token(LlaveDer);
  }

/* SentenciaDoWhile [Estructura #2] */
  static final public void SentenciaDoWhile() throws ParseException {
    jj_consume_token(Do);
    jj_consume_token(LlaveIzq);
    jj_consume_token(LlaveDer);
    jj_consume_token(While);
    jj_consume_token(ParenIzq);
    Condicion();
    jj_consume_token(ParenDer);
    jj_consume_token(PuntoYComa);
  }

/* SentenciaWhile [Estructura #3] */
  static final public void SentenciaWhile() throws ParseException {
    jj_consume_token(While);
    jj_consume_token(ParenIzq);
    Condicion();
    jj_consume_token(ParenDer);
    jj_consume_token(LlaveIzq);
    jj_consume_token(LlaveDer);
  }

/* SentenciaFor [Estructura #4] */

/* SentenciaIf [Estructura #5] */
  static final public void SentenciaIf() throws ParseException {
    jj_consume_token(Pregunta);
    jj_consume_token(ParenIzq);
    Condicion();
    jj_consume_token(ParenDer);
    jj_consume_token(LlaveIzq);
    jj_consume_token(LlaveDer);
  }

/* SentenciaIf [Estructura #6] */
  static final public void DeclaracionVariable() throws ParseException {
    jj_consume_token(TipoDato);
    jj_consume_token(Caracteres);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case Coma:{
        ;
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        break label_6;
      }
      MasVariables();
    }
    jj_consume_token(PuntoYComa);
  }

/* Comentario [Estructura #7]
void SentenciaComentario():{}{
	(<ComentC>|<ComentSQLInicio>) TodoElTexto() <ComentSQLFin>
}
*/

/* SentenciaLlamadaMetodo [Estructura #8] */
  static final public void SentenciaLlamadaMetodo() throws ParseException {
    jj_consume_token(Caracteres);
    jj_consume_token(ParenIzq);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Caracteres:{
      jj_consume_token(Caracteres);
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case Coma:{
          ;
          break;
          }
        default:
          jj_la1[14] = jj_gen;
          break label_7;
        }
        MasVariables();
      }
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      ;
    }
    jj_consume_token(ParenDer);
    jj_consume_token(PuntoYComa);
  }

/* SentenciaMetodo [Estructura #9 y #10] */
  static final public void SentenciaMetodo() throws ParseException {
    InicioMetodo();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Metodo:{
      jj_consume_token(Metodo);
      EstructuraMetodo();
      break;
      }
    case TipoDato:{
      jj_consume_token(TipoDato);
      EstructuraMetodo();
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/* SentenciaTryCatch  [Estructura #11] */
  static final public void SentenciaTryCatch() throws ParseException {
    jj_consume_token(Intenta);
    jj_consume_token(LlaveIzq);
    jj_consume_token(LlaveDer);
    jj_consume_token(CapExcepcion);
    jj_consume_token(ParenIzq);
    jj_consume_token(Excepcion);
    jj_consume_token(Caracteres);
    jj_consume_token(ParenDer);
    jj_consume_token(LlaveIzq);
    jj_consume_token(LlaveDer);
  }

/* SentenciaDeclaracion   [Estructura #12] */
  static final public void SentenciaDeclaracion() throws ParseException {
    InicioDeclaracion();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ParenIzq:{
      jj_consume_token(ParenIzq);
      jj_consume_token(ParenDer);
      break;
      }
    default:
      jj_la1[17] = jj_gen;
      ;
    }
    jj_consume_token(PuntoYComa);
  }

/* SentenciaInsertarEnTabla   [Estructura #13] */
  static final public void SentenciaInsertarEnTabla() throws ParseException {
    jj_consume_token(Insertar);
    jj_consume_token(DentroDe);
    jj_consume_token(Caracteres);
    jj_consume_token(Valores);
    jj_consume_token(ParenIzq);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Apost:{
      Texto();
      break;
      }
    case Numero:{
      jj_consume_token(Numero);
      break;
      }
    case NumeroDecimal:{
      jj_consume_token(NumeroDecimal);
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case Coma:{
        ;
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        break label_8;
      }
      MasValores();
    }
    jj_consume_token(ParenDer);
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public compTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[20];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static private int[] jj_la1_3;
  static private int[] jj_la1_4;
  static private int[] jj_la1_5;
  static private int[] jj_la1_6;
  static private int[] jj_la1_7;
  static private int[] jj_la1_8;
  static private int[] jj_la1_9;
  static private int[] jj_la1_10;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
      jj_la1_init_3();
      jj_la1_init_4();
      jj_la1_init_5();
      jj_la1_init_6();
      jj_la1_init_7();
      jj_la1_init_8();
      jj_la1_init_9();
      jj_la1_init_10();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x100,0x100,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x8000,0x0,0x0,0x0,0x0,0x0,0x0,0x400,0x8000,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x200,0x200,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x4000,0x4000,0x4000,0x0,0x200,0x0,0x0,0x4000,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x4036,0x4036,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x4000,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_3() {
      jj_la1_3 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_4() {
      jj_la1_4 = new int[] {0x80000000,0x80000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_5() {
      jj_la1_5 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_6() {
      jj_la1_6 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x4,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_7() {
      jj_la1_7 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_8() {
      jj_la1_8 = new int[] {0x100400,0x100400,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_9() {
      jj_la1_9 = new int[] {0x2000,0x2000,0x20000000,0x20000000,0x20000000,0x20000000,0x0,0x2000,0x0,0x0,0x30000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x30000000,0x0,};
   }
   private static void jj_la1_init_10() {
      jj_la1_10 = new int[] {0x1,0x1,0x0,0x1,0x0,0x1,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,};
   }

  /** Constructor with InputStream. */
  public comp(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public comp(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new compTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public comp(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new compTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public comp(compTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(compTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[321];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 20; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
          if ((jj_la1_3[i] & (1<<j)) != 0) {
            la1tokens[96+j] = true;
          }
          if ((jj_la1_4[i] & (1<<j)) != 0) {
            la1tokens[128+j] = true;
          }
          if ((jj_la1_5[i] & (1<<j)) != 0) {
            la1tokens[160+j] = true;
          }
          if ((jj_la1_6[i] & (1<<j)) != 0) {
            la1tokens[192+j] = true;
          }
          if ((jj_la1_7[i] & (1<<j)) != 0) {
            la1tokens[224+j] = true;
          }
          if ((jj_la1_8[i] & (1<<j)) != 0) {
            la1tokens[256+j] = true;
          }
          if ((jj_la1_9[i] & (1<<j)) != 0) {
            la1tokens[288+j] = true;
          }
          if ((jj_la1_10[i] & (1<<j)) != 0) {
            la1tokens[320+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 321; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
