/* Generated By:JavaCC: Do not edit this line. compConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface compConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Letra = 1;
  /** RegularExpression Id. */
  int Numero = 2;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 3;
  /** RegularExpression Id. */
  int ComentC = 4;
  /** RegularExpression Id. */
  int ComentSQLInicio = 5;
  /** RegularExpression Id. */
  int ComentSQLFin = 6;
  /** RegularExpression Id. */
  int ComentHTML = 7;
  /** RegularExpression Id. */
  int Comentario = 8;
  /** RegularExpression Id. */
  int Pregunta = 9;
  /** RegularExpression Id. */
  int Entonces = 10;
  /** RegularExpression Id. */
  int ParenIzq = 11;
  /** RegularExpression Id. */
  int ParenDer = 12;
  /** RegularExpression Id. */
  int CorIzq = 13;
  /** RegularExpression Id. */
  int CorDer = 14;
  /** RegularExpression Id. */
  int Comilla = 15;
  /** RegularExpression Id. */
  int Apost = 16;
  /** RegularExpression Id. */
  int Comillas = 17;
  /** RegularExpression Id. */
  int Char = 18;
  /** RegularExpression Id. */
  int Int = 19;
  /** RegularExpression Id. */
  int Float = 20;
  /** RegularExpression Id. */
  int Double = 21;
  /** RegularExpression Id. */
  int String = 22;
  /** RegularExpression Id. */
  int Bool = 23;
  /** RegularExpression Id. */
  int Var = 24;
  /** RegularExpression Id. */
  int Byte = 25;
  /** RegularExpression Id. */
  int Long = 26;
  /** RegularExpression Id. */
  int Short = 27;
  /** RegularExpression Id. */
  int Ulong = 28;
  /** RegularExpression Id. */
  int UINT = 29;
  /** RegularExpression Id. */
  int Sbyte = 30;
  /** RegularExpression Id. */
  int Ushort = 31;
  /** RegularExpression Id. */
  int Nchar = 32;
  /** RegularExpression Id. */
  int Varchar = 33;
  /** RegularExpression Id. */
  int DATE = 34;
  /** RegularExpression Id. */
  int DATETIME = 35;
  /** RegularExpression Id. */
  int Numeric = 36;
  /** RegularExpression Id. */
  int NVARCHAR = 37;
  /** RegularExpression Id. */
  int Bit = 38;
  /** RegularExpression Id. */
  int Money = 39;
  /** RegularExpression Id. */
  int Str = 40;
  /** RegularExpression Id. */
  int TipoDato = 41;
  /** RegularExpression Id. */
  int LlaveIzq = 42;
  /** RegularExpression Id. */
  int LlaveDer = 43;
  /** RegularExpression Id. */
  int PuntoYComa = 44;
  /** RegularExpression Id. */
  int Coma = 45;
  /** RegularExpression Id. */
  int Puntuacion = 46;
  /** RegularExpression Id. */
  int IgualIgual = 47;
  /** RegularExpression Id. */
  int MenorQue = 48;
  /** RegularExpression Id. */
  int MayorQue = 49;
  /** RegularExpression Id. */
  int DiferenteDe = 50;
  /** RegularExpression Id. */
  int MenorIgual = 51;
  /** RegularExpression Id. */
  int MayorIgual = 52;
  /** RegularExpression Id. */
  int Comparador = 53;
  /** RegularExpression Id. */
  int AccesoMiembro = 54;
  /** RegularExpression Id. */
  int Clase = 55;
  /** RegularExpression Id. */
  int Arroba = 56;
  /** RegularExpression Id. */
  int SignoDinero = 57;
  /** RegularExpression Id. */
  int Sustitucion = 58;
  /** RegularExpression Id. */
  int Public = 59;
  /** RegularExpression Id. */
  int Protected = 60;
  /** RegularExpression Id. */
  int Private = 61;
  /** RegularExpression Id. */
  int Internal = 62;
  /** RegularExpression Id. */
  int TipoAcceso = 63;
  /** RegularExpression Id. */
  int Do = 64;
  /** RegularExpression Id. */
  int For = 65;
  /** RegularExpression Id. */
  int Foreach = 66;
  /** RegularExpression Id. */
  int While = 67;
  /** RegularExpression Id. */
  int Ciclo = 68;
  /** RegularExpression Id. */
  int SelectivaMultiple = 69;
  /** RegularExpression Id. */
  int Else = 70;
  /** RegularExpression Id. */
  int Finally = 71;
  /** RegularExpression Id. */
  int Default = 72;
  /** RegularExpression Id. */
  int Defecto = 73;
  /** RegularExpression Id. */
  int Asignar = 74;
  /** RegularExpression Id. */
  int Case = 75;
  /** RegularExpression Id. */
  int Metodo = 76;
  /** RegularExpression Id. */
  int ClaseConsole = 77;
  /** RegularExpression Id. */
  int Sobrecargar = 78;
  /** RegularExpression Id. */
  int Concat = 79;
  /** RegularExpression Id. */
  int Concat_Ws = 80;
  /** RegularExpression Id. */
  int Length = 81;
  /** RegularExpression Id. */
  int Write = 82;
  /** RegularExpression Id. */
  int WriteLine = 83;
  /** RegularExpression Id. */
  int Read = 84;
  /** RegularExpression Id. */
  int ReadLine = 85;
  /** RegularExpression Id. */
  int ReadKey = 86;
  /** RegularExpression Id. */
  int Ascii = 87;
  /** RegularExpression Id. */
  int Clear = 88;
  /** RegularExpression Id. */
  int Delete = 89;
  /** RegularExpression Id. */
  int Include = 90;
  /** RegularExpression Id. */
  int Substring = 91;
  /** RegularExpression Id. */
  int ToChar = 92;
  /** RegularExpression Id. */
  int Upper = 93;
  /** RegularExpression Id. */
  int ToUpper = 94;
  /** RegularExpression Id. */
  int Lower = 95;
  /** RegularExpression Id. */
  int ToLower = 96;
  /** RegularExpression Id. */
  int ToString = 97;
  /** RegularExpression Id. */
  int Next = 98;
  /** RegularExpression Id. */
  int Replace = 99;
  /** RegularExpression Id. */
  int Len = 100;
  /** RegularExpression Id. */
  int Reverse = 101;
  /** RegularExpression Id. */
  int Format = 102;
  /** RegularExpression Id. */
  int FuncionString = 103;
  /** RegularExpression Id. */
  int AVG = 104;
  /** RegularExpression Id. */
  int Count = 105;
  /** RegularExpression Id. */
  int Max = 106;
  /** RegularExpression Id. */
  int Min = 107;
  /** RegularExpression Id. */
  int Sum = 108;
  /** RegularExpression Id. */
  int FuncionAgregar = 109;
  /** RegularExpression Id. */
  int DateDiff = 110;
  /** RegularExpression Id. */
  int DateAdd = 111;
  /** RegularExpression Id. */
  int DateName = 112;
  /** RegularExpression Id. */
  int Day = 113;
  /** RegularExpression Id. */
  int GetDate = 114;
  /** RegularExpression Id. */
  int Month = 115;
  /** RegularExpression Id. */
  int Year = 116;
  /** RegularExpression Id. */
  int FuncionDate = 117;
  /** RegularExpression Id. */
  int Abs = 118;
  /** RegularExpression Id. */
  int Acos = 119;
  /** RegularExpression Id. */
  int Asin = 120;
  /** RegularExpression Id. */
  int Atan = 121;
  /** RegularExpression Id. */
  int Cos = 122;
  /** RegularExpression Id. */
  int Cot = 123;
  /** RegularExpression Id. */
  int Floor = 124;
  /** RegularExpression Id. */
  int Log = 125;
  /** RegularExpression Id. */
  int LogDiez = 126;
  /** RegularExpression Id. */
  int Pi = 127;
  /** RegularExpression Id. */
  int Power = 128;
  /** RegularExpression Id. */
  int Radians = 129;
  /** RegularExpression Id. */
  int Round = 130;
  /** RegularExpression Id. */
  int Sin = 131;
  /** RegularExpression Id. */
  int Sqrt = 132;
  /** RegularExpression Id. */
  int Square = 133;
  /** RegularExpression Id. */
  int Tan = 134;
  /** RegularExpression Id. */
  int FuncionMath = 135;
  /** RegularExpression Id. */
  int Parse = 136;
  /** RegularExpression Id. */
  int Try_Cast = 137;
  /** RegularExpression Id. */
  int Try_Convert = 138;
  /** RegularExpression Id. */
  int Try_Parse = 139;
  /** RegularExpression Id. */
  int FuncionConvert = 140;
  /** RegularExpression Id. */
  int Choose = 141;
  /** RegularExpression Id. */
  int Greatest = 142;
  /** RegularExpression Id. */
  int Iif = 143;
  /** RegularExpression Id. */
  int Least = 144;
  /** RegularExpression Id. */
  int FuncionLogica = 145;
  /** RegularExpression Id. */
  int First_Value = 146;
  /** RegularExpression Id. */
  int Last_Value = 147;
  /** RegularExpression Id. */
  int Lag = 148;
  /** RegularExpression Id. */
  int Lead = 149;
  /** RegularExpression Id. */
  int FuncionAnalitic = 150;
  /** RegularExpression Id. */
  int Estructura = 151;
  /** RegularExpression Id. */
  int CapExcepcion = 152;
  /** RegularExpression Id. */
  int Namespace = 153;
  /** RegularExpression Id. */
  int Intenta = 154;
  /** RegularExpression Id. */
  int Romper = 155;
  /** RegularExpression Id. */
  int Base = 156;
  /** RegularExpression Id. */
  int Checked = 157;
  /** RegularExpression Id. */
  int BackColor = 158;
  /** RegularExpression Id. */
  int Font = 159;
  /** RegularExpression Id. */
  int Text = 160;
  /** RegularExpression Id. */
  int Enabled = 161;
  /** RegularExpression Id. */
  int TextAling = 162;
  /** RegularExpression Id. */
  int ReadOnly = 163;
  /** RegularExpression Id. */
  int Cursor = 164;
  /** RegularExpression Id. */
  int TabIndex = 165;
  /** RegularExpression Id. */
  int Visible = 166;
  /** RegularExpression Id. */
  int Locked = 167;
  /** RegularExpression Id. */
  int Size = 168;
  /** RegularExpression Id. */
  int Opacity = 169;
  /** RegularExpression Id. */
  int Icon = 170;
  /** RegularExpression Id. */
  int AcceptButton = 171;
  /** RegularExpression Id. */
  int CancelButton = 172;
  /** RegularExpression Id. */
  int DialogResult = 173;
  /** RegularExpression Id. */
  int Propiedad = 174;
  /** RegularExpression Id. */
  int True = 175;
  /** RegularExpression Id. */
  int False = 176;
  /** RegularExpression Id. */
  int ResultadoLogico = 177;
  /** RegularExpression Id. */
  int List = 178;
  /** RegularExpression Id. */
  int Stack = 179;
  /** RegularExpression Id. */
  int Queue = 180;
  /** RegularExpression Id. */
  int Lista = 181;
  /** RegularExpression Id. */
  int Retorno = 182;
  /** RegularExpression Id. */
  int Libreria = 183;
  /** RegularExpression Id. */
  int Colletions = 184;
  /** RegularExpression Id. */
  int Dynamic = 185;
  /** RegularExpression Id. */
  int IO = 186;
  /** RegularExpression Id. */
  int Linq = 187;
  /** RegularExpression Id. */
  int Resources = 188;
  /** RegularExpression Id. */
  int Security = 189;
  /** RegularExpression Id. */
  int Threading = 190;
  /** RegularExpression Id. */
  int Diagnostic = 191;
  /** RegularExpression Id. */
  int Drawing = 192;
  /** RegularExpression Id. */
  int TipoLibreria = 193;
  /** RegularExpression Id. */
  int OperadorNew = 194;
  /** RegularExpression Id. */
  int Mas = 195;
  /** RegularExpression Id. */
  int Menos = 196;
  /** RegularExpression Id. */
  int OpAritmetico = 197;
  /** RegularExpression Id. */
  int Incremento = 198;
  /** RegularExpression Id. */
  int Decremento = 199;
  /** RegularExpression Id. */
  int OpAritmeticoUnitario = 200;
  /** RegularExpression Id. */
  int Multiplicacion = 201;
  /** RegularExpression Id. */
  int Divison = 202;
  /** RegularExpression Id. */
  int Modulo = 203;
  /** RegularExpression Id. */
  int OpAritmeticoBinario = 204;
  /** RegularExpression Id. */
  int OpLogicoBoolUnitario = 205;
  /** RegularExpression Id. */
  int OrLogico = 206;
  /** RegularExpression Id. */
  int AndLogico = 207;
  /** RegularExpression Id. */
  int ExclusivoOrLogico = 208;
  /** RegularExpression Id. */
  int AND = 209;
  /** RegularExpression Id. */
  int OR = 210;
  /** RegularExpression Id. */
  int OpLogicoBoolBinario = 211;
  /** RegularExpression Id. */
  int AndCondicional = 212;
  /** RegularExpression Id. */
  int OrCondicional = 213;
  /** RegularExpression Id. */
  int OpLogicoBoolBinarioCondicional = 214;
  /** RegularExpression Id. */
  int Select = 215;
  /** RegularExpression Id. */
  int From = 216;
  /** RegularExpression Id. */
  int Where = 217;
  /** RegularExpression Id. */
  int Consulta = 218;
  /** RegularExpression Id. */
  int GroupBy = 219;
  /** RegularExpression Id. */
  int Having = 220;
  /** RegularExpression Id. */
  int OrderBy = 221;
  /** RegularExpression Id. */
  int Over = 222;
  /** RegularExpression Id. */
  int TipoSelect = 223;
  /** RegularExpression Id. */
  int Inner = 224;
  /** RegularExpression Id. */
  int Join = 225;
  /** RegularExpression Id. */
  int Left = 226;
  /** RegularExpression Id. */
  int Outer = 227;
  /** RegularExpression Id. */
  int Right = 228;
  /** RegularExpression Id. */
  int Full = 229;
  /** RegularExpression Id. */
  int Cross = 230;
  /** RegularExpression Id. */
  int Apply = 231;
  /** RegularExpression Id. */
  int Pivot = 232;
  /** RegularExpression Id. */
  int Unpivot = 233;
  /** RegularExpression Id. */
  int TipoFrom = 234;
  /** RegularExpression Id. */
  int TipoWhere = 235;
  /** RegularExpression Id. */
  int BaseDatos = 236;
  /** RegularExpression Id. */
  int Procedimiento = 237;
  /** RegularExpression Id. */
  int Table = 238;
  /** RegularExpression Id. */
  int User = 239;
  /** RegularExpression Id. */
  int View = 240;
  /** RegularExpression Id. */
  int TipoCreate = 241;
  /** RegularExpression Id. */
  int Add = 242;
  /** RegularExpression Id. */
  int DentroDe = 243;
  /** RegularExpression Id. */
  int Valores = 244;
  /** RegularExpression Id. */
  int Ejecutar = 245;
  /** RegularExpression Id. */
  int Alter = 246;
  /** RegularExpression Id. */
  int Create = 247;
  /** RegularExpression Id. */
  int Drop = 248;
  /** RegularExpression Id. */
  int Set = 249;
  /** RegularExpression Id. */
  int Use = 250;
  /** RegularExpression Id. */
  int Declaracion = 251;
  /** RegularExpression Id. */
  int Agregar = 252;
  /** RegularExpression Id. */
  int Check = 253;
  /** RegularExpression Id. */
  int Constraint = 254;
  /** RegularExpression Id. */
  int Llave = 255;
  /** RegularExpression Id. */
  int Primaria = 256;
  /** RegularExpression Id. */
  int Foranea = 257;
  /** RegularExpression Id. */
  int TipoLlave = 258;
  /** RegularExpression Id. */
  int Referencia = 259;
  /** RegularExpression Id. */
  int Unique = 260;
  /** RegularExpression Id. */
  int Insertar = 261;
  /** RegularExpression Id. */
  int Doctype = 262;
  /** RegularExpression Id. */
  int Body = 263;
  /** RegularExpression Id. */
  int Br = 264;
  /** RegularExpression Id. */
  int Button = 265;
  /** RegularExpression Id. */
  int Center = 266;
  /** RegularExpression Id. */
  int Col = 267;
  /** RegularExpression Id. */
  int Footer = 268;
  /** RegularExpression Id. */
  int Frame = 269;
  /** RegularExpression Id. */
  int H1 = 270;
  /** RegularExpression Id. */
  int H2 = 271;
  /** RegularExpression Id. */
  int H3 = 272;
  /** RegularExpression Id. */
  int H4 = 273;
  /** RegularExpression Id. */
  int H5 = 274;
  /** RegularExpression Id. */
  int H6 = 275;
  /** RegularExpression Id. */
  int Head = 276;
  /** RegularExpression Id. */
  int Header = 277;
  /** RegularExpression Id. */
  int Ht = 278;
  /** RegularExpression Id. */
  int Html = 279;
  /** RegularExpression Id. */
  int Img = 280;
  /** RegularExpression Id. */
  int Input = 281;
  /** RegularExpression Id. */
  int Label = 282;
  /** RegularExpression Id. */
  int Etiqueta = 283;
  /** RegularExpression Id. */
  int TerminarEtiqueta = 284;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<Letra>",
    "<Numero>",
    "<IDENTIFICADOR>",
    "<ComentC>",
    "<ComentSQLInicio>",
    "<ComentSQLFin>",
    "<ComentHTML>",
    "<Comentario>",
    "<Pregunta>",
    "<Entonces>",
    "<ParenIzq>",
    "<ParenDer>",
    "<CorIzq>",
    "<CorDer>",
    "<Comilla>",
    "<Apost>",
    "<Comillas>",
    "<Char>",
    "<Int>",
    "<Float>",
    "<Double>",
    "<String>",
    "<Bool>",
    "<Var>",
    "<Byte>",
    "<Long>",
    "<Short>",
    "<Ulong>",
    "<UINT>",
    "<Sbyte>",
    "<Ushort>",
    "<Nchar>",
    "<Varchar>",
    "<DATE>",
    "<DATETIME>",
    "<Numeric>",
    "<NVARCHAR>",
    "<Bit>",
    "<Money>",
    "<Str>",
    "<TipoDato>",
    "<LlaveIzq>",
    "<LlaveDer>",
    "<PuntoYComa>",
    "<Coma>",
    "<Puntuacion>",
    "<IgualIgual>",
    "<MenorQue>",
    "<MayorQue>",
    "<DiferenteDe>",
    "<MenorIgual>",
    "<MayorIgual>",
    "<Comparador>",
    "<AccesoMiembro>",
    "<Clase>",
    "<Arroba>",
    "<SignoDinero>",
    "<Sustitucion>",
    "<Public>",
    "<Protected>",
    "<Private>",
    "<Internal>",
    "<TipoAcceso>",
    "<Do>",
    "<For>",
    "<Foreach>",
    "<While>",
    "<Ciclo>",
    "<SelectivaMultiple>",
    "<Else>",
    "<Finally>",
    "<Default>",
    "<Defecto>",
    "<Asignar>",
    "<Case>",
    "<Metodo>",
    "<ClaseConsole>",
    "<Sobrecargar>",
    "<Concat>",
    "<Concat_Ws>",
    "<Length>",
    "<Write>",
    "<WriteLine>",
    "<Read>",
    "<ReadLine>",
    "<ReadKey>",
    "<Ascii>",
    "<Clear>",
    "<Delete>",
    "<Include>",
    "<Substring>",
    "<ToChar>",
    "<Upper>",
    "<ToUpper>",
    "<Lower>",
    "<ToLower>",
    "<ToString>",
    "<Next>",
    "<Replace>",
    "<Len>",
    "<Reverse>",
    "<Format>",
    "<FuncionString>",
    "<AVG>",
    "<Count>",
    "<Max>",
    "<Min>",
    "<Sum>",
    "<FuncionAgregar>",
    "<DateDiff>",
    "<DateAdd>",
    "<DateName>",
    "<Day>",
    "<GetDate>",
    "<Month>",
    "<Year>",
    "<FuncionDate>",
    "<Abs>",
    "<Acos>",
    "<Asin>",
    "<Atan>",
    "<Cos>",
    "<Cot>",
    "<Floor>",
    "<Log>",
    "<LogDiez>",
    "<Pi>",
    "<Power>",
    "<Radians>",
    "<Round>",
    "<Sin>",
    "<Sqrt>",
    "<Square>",
    "<Tan>",
    "<FuncionMath>",
    "<Parse>",
    "<Try_Cast>",
    "<Try_Convert>",
    "<Try_Parse>",
    "<FuncionConvert>",
    "<Choose>",
    "<Greatest>",
    "<Iif>",
    "<Least>",
    "<FuncionLogica>",
    "<First_Value>",
    "<Last_Value>",
    "<Lag>",
    "<Lead>",
    "<FuncionAnalitic>",
    "<Estructura>",
    "<CapExcepcion>",
    "<Namespace>",
    "<Intenta>",
    "<Romper>",
    "<Base>",
    "<Checked>",
    "<BackColor>",
    "<Font>",
    "<Text>",
    "<Enabled>",
    "<TextAling>",
    "<ReadOnly>",
    "<Cursor>",
    "<TabIndex>",
    "<Visible>",
    "<Locked>",
    "<Size>",
    "<Opacity>",
    "<Icon>",
    "<AcceptButton>",
    "<CancelButton>",
    "<DialogResult>",
    "<Propiedad>",
    "<True>",
    "<False>",
    "<ResultadoLogico>",
    "<List>",
    "<Stack>",
    "<Queue>",
    "<Lista>",
    "<Retorno>",
    "<Libreria>",
    "<Colletions>",
    "<Dynamic>",
    "<IO>",
    "<Linq>",
    "<Resources>",
    "<Security>",
    "<Threading>",
    "<Diagnostic>",
    "<Drawing>",
    "<TipoLibreria>",
    "<OperadorNew>",
    "<Mas>",
    "<Menos>",
    "<OpAritmetico>",
    "<Incremento>",
    "<Decremento>",
    "<OpAritmeticoUnitario>",
    "<Multiplicacion>",
    "<Divison>",
    "<Modulo>",
    "<OpAritmeticoBinario>",
    "<OpLogicoBoolUnitario>",
    "<OrLogico>",
    "<AndLogico>",
    "<ExclusivoOrLogico>",
    "<AND>",
    "<OR>",
    "<OpLogicoBoolBinario>",
    "<AndCondicional>",
    "<OrCondicional>",
    "<OpLogicoBoolBinarioCondicional>",
    "<Select>",
    "<From>",
    "<Where>",
    "<Consulta>",
    "<GroupBy>",
    "<Having>",
    "<OrderBy>",
    "<Over>",
    "<TipoSelect>",
    "<Inner>",
    "<Join>",
    "<Left>",
    "<Outer>",
    "<Right>",
    "<Full>",
    "<Cross>",
    "<Apply>",
    "<Pivot>",
    "<Unpivot>",
    "<TipoFrom>",
    "<TipoWhere>",
    "<BaseDatos>",
    "<Procedimiento>",
    "<Table>",
    "<User>",
    "<View>",
    "<TipoCreate>",
    "<Add>",
    "<DentroDe>",
    "<Valores>",
    "<Ejecutar>",
    "<Alter>",
    "<Create>",
    "<Drop>",
    "<Set>",
    "<Use>",
    "<Declaracion>",
    "<Agregar>",
    "<Check>",
    "<Constraint>",
    "<Llave>",
    "<Primaria>",
    "<Foranea>",
    "<TipoLlave>",
    "<Referencia>",
    "<Unique>",
    "<Insertar>",
    "<Doctype>",
    "<Body>",
    "<Br>",
    "<Button>",
    "<Center>",
    "<Col>",
    "<Footer>",
    "<Frame>",
    "<H1>",
    "<H2>",
    "<H3>",
    "<H4>",
    "<H5>",
    "<H6>",
    "<Head>",
    "<Header>",
    "<Ht>",
    "<Html>",
    "<Img>",
    "<Input>",
    "<Label>",
    "<Etiqueta>",
    "<TerminarEtiqueta>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
