/* Generated By:JavaCC: Do not edit this line. compTokenManager.java */
import java.util.*;

/** Token Manager. */
public class compTokenManager implements compConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0, long active1, long active2, long active3, long active4)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x100000000000000L) != 0L)
         {
            jjmatchedKind = 323;
            return 153;
         }
         if ((active4 & 0x400000000000000L) != 0L)
         {
            jjmatchedKind = 323;
            return 77;
         }
         return -1;
      case 1:
         if ((active4 & 0x400000000000000L) != 0L)
         {
            jjmatchedKind = 323;
            jjmatchedPos = 1;
            return 363;
         }
         if ((active0 & 0x100000000000000L) != 0L)
            return 285;
         return -1;
      case 2:
         if ((active4 & 0x400000000000000L) != 0L)
         {
            jjmatchedKind = 323;
            jjmatchedPos = 2;
            return 363;
         }
         return -1;
      case 3:
         if ((active4 & 0x400000000000000L) != 0L)
         {
            jjmatchedKind = 323;
            jjmatchedPos = 3;
            return 363;
         }
         return -1;
      case 4:
         if ((active4 & 0x400000000000000L) != 0L)
         {
            jjmatchedKind = 323;
            jjmatchedPos = 4;
            return 363;
         }
         return -1;
      case 5:
         if ((active4 & 0x400000000000000L) != 0L)
         {
            jjmatchedKind = 323;
            jjmatchedPos = 5;
            return 363;
         }
         return -1;
      case 6:
         if ((active4 & 0x400000000000000L) != 0L)
         {
            jjmatchedKind = 323;
            jjmatchedPos = 6;
            return 363;
         }
         return -1;
      case 7:
         if ((active4 & 0x400000000000000L) != 0L)
         {
            jjmatchedKind = 323;
            jjmatchedPos = 7;
            return 363;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0, long active1, long active2, long active3, long active4)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1, active2, active3, active4), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x400000000000000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x100000000000000L, 0x0L);
      case 194:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x200000000000000L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0, long active4)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, 0L, 0L, 0L, active4);
      return 1;
   }
   switch(curChar)
   {
      case 110:
         if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 56, 285);
         break;
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active4, 0x400000000000000L);
      case 161:
         if ((active4 & 0x200000000000000L) != 0L)
            return jjStopAtPos(1, 313);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, 0L, 0L, 0L, active4);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old4, long active4)
{
   if (((active0 &= old0) | (active4 &= old4)) == 0L)
      return jjStartNfa_0(0, old0, 0L, 0L, 0L, old4); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, 0L, 0L, 0L, 0L, active4);
      return 2;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa3_0(active4, 0x400000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, 0L, 0L, 0L, 0L, active4);
}
static private int jjMoveStringLiteralDfa3_0(long old4, long active4)
{
   if (((active4 &= old4)) == 0L)
      return jjStartNfa_0(1, 0L, 0L, 0L, 0L, old4); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, 0L, 0L, 0L, 0L, active4);
      return 3;
   }
   switch(curChar)
   {
      case 101:
         return jjMoveStringLiteralDfa4_0(active4, 0x400000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, 0L, 0L, 0L, 0L, active4);
}
static private int jjMoveStringLiteralDfa4_0(long old4, long active4)
{
   if (((active4 &= old4)) == 0L)
      return jjStartNfa_0(2, 0L, 0L, 0L, 0L, old4); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, 0L, 0L, 0L, 0L, active4);
      return 4;
   }
   switch(curChar)
   {
      case 112:
         return jjMoveStringLiteralDfa5_0(active4, 0x400000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, 0L, 0L, 0L, 0L, active4);
}
static private int jjMoveStringLiteralDfa5_0(long old4, long active4)
{
   if (((active4 &= old4)) == 0L)
      return jjStartNfa_0(3, 0L, 0L, 0L, 0L, old4); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, 0L, 0L, 0L, 0L, active4);
      return 5;
   }
   switch(curChar)
   {
      case 116:
         return jjMoveStringLiteralDfa6_0(active4, 0x400000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, 0L, 0L, 0L, 0L, active4);
}
static private int jjMoveStringLiteralDfa6_0(long old4, long active4)
{
   if (((active4 &= old4)) == 0L)
      return jjStartNfa_0(4, 0L, 0L, 0L, 0L, old4); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, 0L, 0L, 0L, 0L, active4);
      return 6;
   }
   switch(curChar)
   {
      case 105:
         return jjMoveStringLiteralDfa7_0(active4, 0x400000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, 0L, 0L, 0L, 0L, active4);
}
static private int jjMoveStringLiteralDfa7_0(long old4, long active4)
{
   if (((active4 &= old4)) == 0L)
      return jjStartNfa_0(5, 0L, 0L, 0L, 0L, old4); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, 0L, 0L, 0L, 0L, active4);
      return 7;
   }
   switch(curChar)
   {
      case 111:
         return jjMoveStringLiteralDfa8_0(active4, 0x400000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, 0L, 0L, 0L, 0L, active4);
}
static private int jjMoveStringLiteralDfa8_0(long old4, long active4)
{
   if (((active4 &= old4)) == 0L)
      return jjStartNfa_0(6, 0L, 0L, 0L, 0L, old4); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, 0L, 0L, 0L, 0L, active4);
      return 8;
   }
   switch(curChar)
   {
      case 110:
         if ((active4 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 314, 363);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, 0L, 0L, 0L, 0L, active4);
}
static private int jjMoveNfa_0(int startState, int curPos)
{
   //int[] nextStates; // not used
   int startsAt = 0;
   jjnewStateCnt = 363;
   int i = 1;
   jjstateSet[0] = startState;
   //int j; // not used
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 317)
                        kind = 317;
                     jjCheckNAddStates(0, 2);
                  }
                  else if ((0x100002600L & l) != 0L)
                  {
                     if (kind > 1)
                        kind = 1;
                  }
                  else if ((0x842000000000L & l) != 0L)
                  {
                     if (kind > 219)
                        kind = 219;
                  }
                  else if ((0x280000000000L & l) != 0L)
                  {
                     if (kind > 212)
                        kind = 212;
                  }
                  else if ((0x5000000000000000L & l) != 0L)
                  {
                     if (kind > 54)
                        kind = 54;
                  }
                  else if ((0x800100000000000L & l) != 0L)
                  {
                     if (kind > 47)
                        kind = 47;
                  }
                  else if ((0x8400000000L & l) != 0L)
                  {
                     if (kind > 16)
                        kind = 16;
                  }
                  else if (curChar == 61)
                  {
                     if (kind > 76)
                        kind = 76;
                     jjCheckNAdd(31);
                  }
                  else if (curChar == 35)
                  {
                     if (kind > 6)
                        kind = 6;
                  }
                  else if (curChar == 33)
                     jjCheckNAddTwoStates(149, 31);
                  else if (curChar == 58)
                  {
                     if (kind > 309)
                        kind = 309;
                  }
                  else if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 65;
                  else if (curChar == 36)
                  {
                     if (kind > 60)
                        kind = 60;
                  }
                  else if (curChar == 46)
                  {
                     if (kind > 55)
                        kind = 55;
                  }
                  else if (curChar == 41)
                  {
                     if (kind > 11)
                        kind = 11;
                  }
                  else if (curChar == 40)
                  {
                     if (kind > 10)
                        kind = 10;
                  }
                  if (curChar == 43)
                     jjAddStates(3, 4);
                  else if (curChar == 60)
                     jjCheckNAddTwoStates(31, 247);
                  else if (curChar == 42)
                     jjCheckNAddTwoStates(147, 144);
                  else if (curChar == 47)
                     jjCheckNAddStates(5, 8);
                  else if (curChar == 38)
                  {
                     if (kind > 226)
                        kind = 226;
                  }
                  else if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 61;
                  else if (curChar == 62)
                     jjCheckNAdd(31);
                  else if (curChar == 44)
                  {
                     if (kind > 46)
                        kind = 46;
                  }
                  else if (curChar == 59)
                  {
                     if (kind > 44)
                        kind = 44;
                  }
                  else if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 363:
               case 112:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 323)
                     kind = 323;
                  jjCheckNAdd(112);
                  break;
               case 153:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 323)
                     kind = 323;
                  jjCheckNAdd(112);
                  break;
               case 77:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 323)
                     kind = 323;
                  jjCheckNAdd(112);
                  break;
               case 285:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 323)
                     kind = 323;
                  jjCheckNAdd(112);
                  break;
               case 1:
                  if (curChar == 10 && kind > 1)
                     kind = 1;
                  break;
               case 2:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  if (curChar == 40)
                     kind = 10;
                  break;
               case 4:
                  if (curChar == 41)
                     kind = 11;
                  break;
               case 7:
                  if ((0x8400000000L & l) != 0L)
                     kind = 16;
                  break;
               case 25:
                  if (curChar == 59 && kind > 44)
                     kind = 44;
                  break;
               case 27:
                  if (curChar == 44 && kind > 46)
                     kind = 46;
                  break;
               case 28:
                  if ((0x800100000000000L & l) != 0L && kind > 47)
                     kind = 47;
                  break;
               case 29:
                  if ((0x5000000000000000L & l) != 0L && kind > 54)
                     kind = 54;
                  break;
               case 30:
                  if (curChar == 62)
                     jjCheckNAdd(31);
                  break;
               case 31:
                  if (curChar == 61 && kind > 54)
                     kind = 54;
                  break;
               case 32:
                  if (curChar == 46 && kind > 55)
                     kind = 55;
                  break;
               case 33:
                  if (curChar == 36)
                     kind = 60;
                  break;
               case 59:
                  if ((0x280000000000L & l) != 0L && kind > 212)
                     kind = 212;
                  break;
               case 60:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 61:
                  if (curChar == 45 && kind > 215)
                     kind = 215;
                  break;
               case 62:
                  if ((0x842000000000L & l) != 0L && kind > 219)
                     kind = 219;
                  break;
               case 63:
                  if (curChar == 38 && kind > 226)
                     kind = 226;
                  break;
               case 64:
                  if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 65:
                  if (curChar == 38 && kind > 229)
                     kind = 229;
                  break;
               case 92:
                  if (curChar == 58)
                     kind = 309;
                  break;
               case 141:
                  if (curChar == 47)
                     jjCheckNAddStates(5, 8);
                  break;
               case 142:
                  if (curChar == 47 && kind > 2)
                     kind = 2;
                  break;
               case 143:
                  if (curChar == 42 && kind > 3)
                     kind = 3;
                  break;
               case 144:
                  if (curChar == 47 && kind > 7)
                     kind = 7;
                  break;
               case 145:
                  if (curChar == 42 && kind > 7)
                     kind = 7;
                  break;
               case 146:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(147, 144);
                  break;
               case 147:
                  if (curChar == 47 && kind > 4)
                     kind = 4;
                  break;
               case 148:
                  if (curChar == 33)
                     jjCheckNAddTwoStates(149, 31);
                  break;
               case 149:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 150;
                  break;
               case 150:
                  if (curChar == 45 && kind > 5)
                     kind = 5;
                  break;
               case 151:
                  if (curChar == 35)
                     kind = 6;
                  break;
               case 245:
                  if (curChar != 61)
                     break;
                  if (kind > 76)
                     kind = 76;
                  jjCheckNAdd(31);
                  break;
               case 246:
                  if (curChar == 60)
                     jjCheckNAddTwoStates(31, 247);
                  break;
               case 247:
                  if (curChar == 47 && kind > 308)
                     kind = 308;
                  break;
               case 315:
                  if (curChar == 43)
                     jjAddStates(3, 4);
                  break;
               case 316:
                  if (curChar == 43 && kind > 213)
                     kind = 213;
                  break;
               case 317:
                  if (curChar == 43 && kind > 215)
                     kind = 215;
                  break;
               case 358:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 317)
                     kind = 317;
                  jjCheckNAddStates(0, 2);
                  break;
               case 359:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 317)
                     kind = 317;
                  jjCheckNAddTwoStates(359, 360);
                  break;
               case 360:
                  if (curChar == 46)
                     jjCheckNAdd(361);
                  break;
               case 361:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 317)
                     kind = 317;
                  jjCheckNAdd(361);
                  break;
               case 362:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 319)
                     kind = 319;
                  jjCheckNAdd(362);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 323)
                        kind = 323;
                     jjCheckNAddTwoStates(111, 112);
                  }
                  else if ((0x1000000040000000L & l) != 0L)
                  {
                     if (kind > 226)
                        kind = 226;
                  }
                  else if (curChar == 126)
                  {
                     if (kind > 312)
                        kind = 312;
                  }
                  else if (curChar == 64)
                  {
                     if (kind > 60)
                        kind = 60;
                  }
                  else if (curChar == 95)
                  {
                     if (kind > 47)
                        kind = 47;
                  }
                  else if (curChar == 125)
                  {
                     if (kind > 43)
                        kind = 43;
                  }
                  else if (curChar == 123)
                  {
                     if (kind > 42)
                        kind = 42;
                  }
                  else if (curChar == 93)
                  {
                     if (kind > 13)
                        kind = 13;
                  }
                  else if (curChar == 91)
                  {
                     if (kind > 12)
                        kind = 12;
                  }
                  if ((0x40000000400000L & l) != 0L)
                     jjAddStates(9, 12);
                  else if ((0x20000000200000L & l) != 0L)
                     jjAddStates(13, 14);
                  else if ((0x800000008000L & l) != 0L)
                     jjAddStates(15, 16);
                  else if ((0x200000002L & l) != 0L)
                     jjAddStates(17, 19);
                  else if ((0x80000000800000L & l) != 0L)
                     jjAddStates(20, 21);
                  else if ((0x1000000010000L & l) != 0L)
                     jjAddStates(22, 26);
                  else if ((0x8000000080000L & l) != 0L)
                     jjAddStates(27, 29);
                  else if ((0x800000008L & l) != 0L)
                     jjAddStates(30, 31);
                  else if ((0x1000000010L & l) != 0L)
                     jjAddStates(32, 37);
                  else if ((0x4000000040L & l) != 0L)
                     jjAddStates(38, 42);
                  else if ((0x10000000100000L & l) != 0L)
                     jjAddStates(43, 45);
                  else if ((0x20000000200L & l) != 0L)
                     jjAddStates(46, 49);
                  else if ((0x400000004000L & l) != 0L)
                     jjAddStates(50, 52);
                  else if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 53;
                  else if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 16;
                  else if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 13;
                  else if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 108;
                  else if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 105;
                  else if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 67;
                  else if (curChar == 95)
                  {
                     if (kind > 45)
                        kind = 45;
                  }
                  else if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 9;
                  if (curChar == 115)
                     jjAddStates(53, 56);
                  else if (curChar == 105)
                     jjAddStates(57, 58);
                  else if (curChar == 98)
                     jjAddStates(59, 60);
                  else if (curChar == 117)
                     jjAddStates(61, 63);
                  else if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 97;
                  else if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 87;
                  else if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 77;
                  else if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 73;
                  else if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 69;
                  else if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 48;
                  else if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 44;
                  else if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 37;
                  else if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 35;
                  else if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 21;
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 363:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 323)
                        kind = 323;
                     jjCheckNAdd(112);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 323)
                        kind = 323;
                     jjCheckNAdd(111);
                  }
                  break;
               case 153:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 323)
                        kind = 323;
                     jjCheckNAdd(112);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 323)
                        kind = 323;
                     jjCheckNAdd(111);
                  }
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 160;
                  else if ((0x4000000040L & l) != 0L)
                  {
                     if (kind > 8)
                        kind = 8;
                  }
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 157;
                  if ((0x400000004000L & l) != 0L)
                     jjCheckNAdd(155);
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 292;
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 285;
                  break;
               case 77:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 323)
                        kind = 323;
                     jjCheckNAdd(112);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 323)
                        kind = 323;
                     jjCheckNAdd(111);
                  }
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 104;
                  else if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 285:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 323)
                        kind = 323;
                     jjCheckNAdd(112);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 323)
                        kind = 323;
                     jjCheckNAdd(111);
                  }
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 161;
                  else if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 158;
                  if ((0x10000000100000L & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                  }
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 293;
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 286;
                  break;
               case 5:
                  if (curChar == 91)
                     kind = 12;
                  break;
               case 6:
                  if (curChar == 93)
                     kind = 13;
                  break;
               case 8:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 9:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 10:
               case 133:
                  if (curChar == 110)
                     jjCheckNAdd(11);
                  break;
               case 11:
                  if (curChar == 103 && kind > 40)
                     kind = 40;
                  break;
               case 12:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 13:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 14:
                  if ((0x10000000100000L & l) != 0L && kind > 41)
                     kind = 41;
                  break;
               case 15:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 16:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 17:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 18:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 19:
                  if ((0x200000002000000L & l) != 0L && kind > 41)
                     kind = 41;
                  break;
               case 20:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 21:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 22:
                  if (curChar == 114 && kind > 41)
                     kind = 41;
                  break;
               case 23:
                  if (curChar == 123)
                     kind = 42;
                  break;
               case 24:
                  if (curChar == 125)
                     kind = 43;
                  break;
               case 26:
                  if (curChar == 95 && kind > 45)
                     kind = 45;
                  break;
               case 28:
                  if (curChar == 95 && kind > 47)
                     kind = 47;
                  break;
               case 33:
                  if (curChar == 64)
                     kind = 60;
                  break;
               case 34:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 35:
                  if (curChar == 111 && kind > 66)
                     kind = 66;
                  break;
               case 36:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 37:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 38:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 39:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 40:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 41:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 42:
                  if (curChar == 104 && kind > 68)
                     kind = 68;
                  break;
               case 43:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 44:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 45:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 46:
                  if (curChar == 100 && kind > 78)
                     kind = 78;
                  break;
               case 47:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 48:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 49:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 50:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 51:
                  if (curChar == 104 && kind > 157)
                     kind = 157;
                  break;
               case 52:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 53:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 54:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 55:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 56:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 57:
                  if ((0x400000004000L & l) == 0L)
                     break;
                  if (kind > 194)
                     kind = 194;
                  jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 58:
                  if ((0x8000000080000L & l) != 0L && kind > 194)
                     kind = 194;
                  break;
               case 63:
                  if ((0x1000000040000000L & l) != 0L && kind > 226)
                     kind = 226;
                  break;
               case 66:
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 67:
                  if (curChar == 124 && kind > 229)
                     kind = 229;
                  break;
               case 68:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 69:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 70:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 71:
                  if (curChar == 110 && kind > 303)
                     kind = 303;
                  break;
               case 72:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 73:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 74:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 75:
                  if (curChar == 115 && kind > 304)
                     kind = 304;
                  break;
               case 76:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 78:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 79:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 80:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 81:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 82:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 83:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 84:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 85:
                  if (curChar == 115 && kind > 305)
                     kind = 305;
                  break;
               case 86:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 87:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 88:
                  if (curChar == 106)
                     jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 89:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 90:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 91:
                  if (curChar == 116 && kind > 306)
                     kind = 306;
                  break;
               case 93:
                  if (curChar == 126)
                     kind = 312;
                  break;
               case 94:
                  if (curChar == 78 && kind > 321)
                     kind = 321;
                  break;
               case 95:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 96:
                  if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 97:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 98:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 99:
                  if (curChar == 110 && kind > 321)
                     kind = 321;
                  break;
               case 100:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 101:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 102:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 103:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 104:
                  if (curChar == 68 && kind > 322)
                     kind = 322;
                  break;
               case 105:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 106:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 107:
                  if (curChar == 100 && kind > 322)
                     kind = 322;
                  break;
               case 108:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 109:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 110:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 323)
                     kind = 323;
                  jjCheckNAddTwoStates(111, 112);
                  break;
               case 111:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 323)
                     kind = 323;
                  jjCheckNAdd(111);
                  break;
               case 112:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 323)
                     kind = 323;
                  jjCheckNAdd(112);
                  break;
               case 113:
                  if ((0x400000004000L & l) != 0L)
                     jjAddStates(50, 52);
                  break;
               case 114:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 115:
                  if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 116:
               case 129:
               case 226:
               case 327:
               case 332:
                  if ((0x200000002L & l) != 0L)
                     jjCheckNAdd(117);
                  break;
               case 117:
                  if ((0x4000000040000L & l) != 0L && kind > 41)
                     kind = 41;
                  break;
               case 118:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 119:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 120:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 121:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 122:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 123:
                  if ((0x800000008L & l) != 0L && kind > 41)
                     kind = 41;
                  break;
               case 124:
                  if ((0x40000000400000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 125:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 126:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 127:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 128;
                  break;
               case 128:
                  if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 130:
                  if (curChar == 117)
                     jjAddStates(61, 63);
                  break;
               case 131:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 132:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 134:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 135;
                  break;
               case 135:
                  if (curChar == 110)
                     jjCheckNAdd(136);
                  break;
               case 136:
                  if (curChar == 116 && kind > 40)
                     kind = 40;
                  break;
               case 137:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 138;
                  break;
               case 138:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 139:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 140:
               case 344:
                  if (curChar == 114)
                     jjCheckNAdd(136);
                  break;
               case 152:
                  if ((0x20000000200L & l) != 0L)
                     jjAddStates(46, 49);
                  break;
               case 154:
                  if ((0x400000004000L & l) != 0L)
                     jjCheckNAdd(155);
                  break;
               case 155:
                  if ((0x10000000100000L & l) != 0L && kind > 40)
                     kind = 40;
                  break;
               case 156:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 157;
                  break;
               case 157:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 158:
                  if ((0x800000008000L & l) != 0L && kind > 259)
                     kind = 259;
                  break;
               case 159:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 160;
                  break;
               case 160:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 161;
                  break;
               case 161:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 162:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 163;
                  break;
               case 163:
                  if ((0x10000000100000L & l) != 0L && kind > 277)
                     kind = 277;
                  break;
               case 164:
                  if ((0x10000000100000L & l) != 0L)
                     jjAddStates(43, 45);
                  break;
               case 165:
                  if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 166;
                  break;
               case 166:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 167;
                  break;
               case 167:
                  if ((0x400000004000L & l) != 0L && kind > 9)
                     kind = 9;
                  break;
               case 168:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 169;
                  break;
               case 169:
                  if ((0x200000002000000L & l) != 0L && kind > 159)
                     kind = 159;
                  break;
               case 170:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 171;
                  break;
               case 171:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 172:
                  if ((0x100000001000L & l) != 0L)
                     jjCheckNAdd(173);
                  break;
               case 173:
                  if ((0x2000000020L & l) != 0L && kind > 257)
                     kind = 257;
                  break;
               case 174:
                  if ((0x4000000040L & l) != 0L)
                     jjAddStates(38, 42);
                  break;
               case 175:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 176;
                  break;
               case 176:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 177;
                  break;
               case 177:
                  if ((0x200000002L & l) != 0L)
                     jjCheckNAdd(155);
                  break;
               case 178:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 179;
                  break;
               case 179:
                  if ((0x4000000040000L & l) != 0L && kind > 67)
                     kind = 67;
                  break;
               case 180:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 181;
                  break;
               case 181:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 182;
                  break;
               case 182:
                  if ((0x200000002000L & l) != 0L && kind > 233)
                     kind = 233;
                  break;
               case 183:
                  if (curChar == 117 && kind > 257)
                     kind = 257;
                  break;
               case 184:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 185;
                  break;
               case 185:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 186;
                  break;
               case 186:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 187;
                  break;
               case 187:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 188;
                  break;
               case 188:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 189;
                  break;
               case 189:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 190;
                  break;
               case 190:
                  if ((0x400000004000L & l) != 0L && kind > 257)
                     kind = 257;
                  break;
               case 191:
                  if ((0x1000000010L & l) != 0L)
                     jjAddStates(32, 37);
                  break;
               case 192:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 193;
                  break;
               case 193:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               case 194:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 195;
                  break;
               case 195:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 196;
                  break;
               case 196:
                  if ((0x2000000020L & l) != 0L && kind > 40)
                     kind = 40;
                  break;
               case 197:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 198;
                  break;
               case 198:
                  if ((0x10000000100000L & l) != 0L)
                     jjCheckNAdd(199);
                  break;
               case 199:
                  if ((0x2000000020L & l) != 0L && kind > 41)
                     kind = 41;
                  break;
               case 200:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 201;
                  break;
               case 201:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 202;
                  break;
               case 202:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 203;
                  break;
               case 203:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 204;
                  break;
               case 204:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 205;
                  break;
               case 205:
                  if ((0x200000002000L & l) != 0L)
                     jjCheckNAdd(199);
                  break;
               case 206:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 207;
                  break;
               case 207:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 208;
                  break;
               case 208:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 209;
                  break;
               case 209:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 210;
                  break;
               case 210:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 211;
                  break;
               case 211:
                  if ((0x8000000080000L & l) != 0L)
                     jjCheckNAdd(173);
                  break;
               case 212:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 213;
                  break;
               case 213:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 214;
                  break;
               case 214:
                  if ((0x1000000010000L & l) != 0L && kind > 267)
                     kind = 267;
                  break;
               case 215:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 216;
                  break;
               case 216:
                  if ((0x800000008000L & l) != 0L && kind > 311)
                     kind = 311;
                  break;
               case 217:
                  if (curChar == 98)
                     jjAddStates(59, 60);
                  break;
               case 218:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 219;
                  break;
               case 219:
               case 347:
                  if (curChar == 116)
                     jjCheckNAdd(220);
                  break;
               case 220:
                  if (curChar == 101 && kind > 40)
                     kind = 40;
                  break;
               case 221:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 222;
                  break;
               case 222:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 223;
                  break;
               case 223:
                  if (curChar == 108 && kind > 41)
                     kind = 41;
                  break;
               case 224:
                  if ((0x800000008L & l) != 0L)
                     jjAddStates(30, 31);
                  break;
               case 225:
                  if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 226;
                  break;
               case 227:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 228;
                  break;
               case 228:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 229;
                  break;
               case 229:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 230;
                  break;
               case 230:
                  if ((0x10000000100000L & l) != 0L)
                     jjCheckNAdd(231);
                  break;
               case 231:
                  if ((0x2000000020L & l) != 0L && kind > 267)
                     kind = 267;
                  break;
               case 232:
                  if ((0x8000000080000L & l) != 0L)
                     jjAddStates(27, 29);
                  break;
               case 233:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 234;
                  break;
               case 234:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 235;
                  break;
               case 235:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 236;
                  break;
               case 236:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 237;
                  break;
               case 237:
                  if (curChar == 103 && kind > 41)
                     kind = 41;
                  break;
               case 238:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 239;
                  break;
               case 239:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 240;
                  break;
               case 240:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 241;
                  break;
               case 241:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 242;
                  break;
               case 242:
                  if ((0x10000000100000L & l) != 0L && kind > 233)
                     kind = 233;
                  break;
               case 243:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 244;
                  break;
               case 244:
                  if ((0x10000000100000L & l) != 0L && kind > 267)
                     kind = 267;
                  break;
               case 248:
                  if ((0x1000000010000L & l) != 0L)
                     jjAddStates(22, 26);
                  break;
               case 249:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 250;
                  break;
               case 250:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 251;
                  break;
               case 251:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 252;
                  break;
               case 252:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 253;
                  break;
               case 253:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 254;
                  break;
               case 254:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 255;
                  break;
               case 255:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 256;
                  break;
               case 256:
                  if ((0x1000000010L & l) != 0L && kind > 62)
                     kind = 62;
                  break;
               case 257:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 258;
                  break;
               case 258:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 259;
                  break;
               case 259:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 260;
                  break;
               case 260:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 261;
                  break;
               case 261:
                  if ((0x800000008L & l) != 0L && kind > 65)
                     kind = 65;
                  break;
               case 262:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 263;
                  break;
               case 263:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 264;
                  break;
               case 264:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 265;
                  break;
               case 265:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 266;
                  break;
               case 266:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 267;
                  break;
               case 267:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 268;
                  break;
               case 268:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 269;
                  break;
               case 269:
                  if ((0x1000000010L & l) != 0L && kind > 65)
                     kind = 65;
                  break;
               case 270:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 271;
                  break;
               case 271:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 272;
                  break;
               case 272:
                  if ((0x40000000400000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 273;
                  break;
               case 273:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 274;
                  break;
               case 274:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 275;
                  break;
               case 275:
                  if ((0x2000000020L & l) != 0L && kind > 65)
                     kind = 65;
                  break;
               case 276:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 277;
                  break;
               case 277:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 278;
                  break;
               case 278:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 279;
                  break;
               case 279:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 280;
                  break;
               case 280:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 281;
                  break;
               case 281:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 282;
                  break;
               case 282:
                  if ((0x4000000040000L & l) != 0L)
                     jjCheckNAdd(173);
                  break;
               case 283:
                  if (curChar == 105)
                     jjAddStates(57, 58);
                  break;
               case 284:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 285;
                  break;
               case 286:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 287;
                  break;
               case 287:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 288;
                  break;
               case 288:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 289;
                  break;
               case 289:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 290;
                  break;
               case 290:
                  if (curChar == 108 && kind > 64)
                     kind = 64;
                  break;
               case 291:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 292;
                  break;
               case 292:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 293;
                  break;
               case 293:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 294;
                  break;
               case 294:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 295;
                  break;
               case 295:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 296;
                  break;
               case 296:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 297;
                  break;
               case 297:
                  if (curChar == 108 && kind > 65)
                     kind = 65;
                  break;
               case 298:
                  if ((0x80000000800000L & l) != 0L)
                     jjAddStates(20, 21);
                  break;
               case 299:
                  if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 300;
                  break;
               case 300:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 301;
                  break;
               case 301:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 302;
                  break;
               case 302:
                  if ((0x2000000020L & l) != 0L && kind > 69)
                     kind = 69;
                  break;
               case 303:
                  if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 304;
                  break;
               case 304:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 305;
                  break;
               case 305:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 306;
                  break;
               case 306:
                  if ((0x2000000020L & l) != 0L && kind > 233)
                     kind = 233;
                  break;
               case 307:
                  if ((0x200000002L & l) != 0L)
                     jjAddStates(17, 19);
                  break;
               case 308:
                  if ((0x8000000080000L & l) != 0L && kind > 105)
                     kind = 105;
                  break;
               case 309:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 310;
                  break;
               case 310:
                  if ((0x1000000010L & l) != 0L && kind > 226)
                     kind = 226;
                  break;
               case 311:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 312;
                  break;
               case 312:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 313;
                  break;
               case 313:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 314;
                  break;
               case 314:
                  if ((0x4000000040000L & l) != 0L && kind > 267)
                     kind = 267;
                  break;
               case 318:
                  if ((0x800000008000L & l) != 0L)
                     jjAddStates(15, 16);
                  break;
               case 319:
                  if ((0x4000000040000L & l) != 0L && kind > 226)
                     kind = 226;
                  break;
               case 320:
                  if ((0x400000004000L & l) != 0L && kind > 310)
                     kind = 310;
                  break;
               case 321:
                  if ((0x20000000200000L & l) != 0L)
                     jjAddStates(13, 14);
                  break;
               case 322:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 323;
                  break;
               case 323:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 324;
                  break;
               case 324:
                  if ((0x4000000040000L & l) != 0L && kind > 257)
                     kind = 257;
                  break;
               case 325:
                  if ((0x8000000080000L & l) != 0L)
                     jjCheckNAdd(231);
                  break;
               case 326:
                  if ((0x40000000400000L & l) != 0L)
                     jjAddStates(9, 12);
                  break;
               case 328:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 329;
                  break;
               case 329:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 330;
                  break;
               case 330:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 331;
                  break;
               case 331:
                  if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 332;
                  break;
               case 333:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 334;
                  break;
               case 334:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 335;
                  break;
               case 335:
                  if ((0x80000000800000L & l) != 0L && kind > 257)
                     kind = 257;
                  break;
               case 336:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 337;
                  break;
               case 337:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 338;
                  break;
               case 338:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 339;
                  break;
               case 339:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 340;
                  break;
               case 340:
                  if ((0x8000000080000L & l) != 0L && kind > 260)
                     kind = 260;
                  break;
               case 341:
                  if (curChar == 115)
                     jjAddStates(53, 56);
                  break;
               case 342:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 343;
                  break;
               case 343:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 344;
                  break;
               case 345:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 346;
                  break;
               case 346:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 347;
                  break;
               case 348:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 349;
                  break;
               case 349:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 350;
                  break;
               case 350:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 351;
                  break;
               case 351:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 352;
                  break;
               case 352:
                  if (curChar == 99 && kind > 302)
                     kind = 302;
                  break;
               case 353:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 354;
                  break;
               case 354:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 355;
                  break;
               case 355:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 356;
                  break;
               case 356:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 357;
                  break;
               case 357:
                  if (curChar == 114 && kind > 307)
                     kind = 307;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 363 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   359, 360, 362, 316, 317, 142, 143, 144, 145, 327, 328, 333, 336, 322, 325, 319, 
   320, 308, 309, 311, 299, 303, 249, 257, 262, 270, 276, 233, 238, 243, 225, 227, 
   192, 197, 200, 206, 212, 215, 175, 178, 180, 183, 184, 165, 168, 170, 153, 154, 
   156, 159, 114, 118, 124, 342, 345, 348, 353, 284, 291, 218, 221, 131, 134, 137, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, "\151\156", null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, "\302\241", 
"\105\170\143\145\160\164\151\157\156", null, null, null, null, null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0x51c0ff0000013ffdL, 0x2000000503fL, 0xa0000000L, 0x22408b00004L, 
   0xe7ffc0000020081aL, 0xeL, 
};
static final long[] jjtoSkip = {
   0x2L, 0x0L, 0x0L, 0x0L, 
   0x0L, 0x0L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[363];
static private final int[] jjstateSet = new int[726];
static protected char curChar;
/** Constructor. */
public compTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public compTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 363; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String tokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   tokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, tokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  //int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
